!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_second_order_centering_within_dmax (within_dma&
     &xf2pywrap, v1, v2, d1, d2, tol)
      use second_order_centering, only : within_dmax
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical within_dmaxf2pywrap
      within_dmaxf2pywrap = .not.(.not.within_dmax(v1, v2, d1, d2, tol))
      end subroutine f2pywrap_second_order_centering_within_dmax
      subroutine f2pywrap_second_order_centering_compute_perimeter (comp&
     &ute_perimeterf2pywrap, v1, v2)
      use second_order_centering, only : compute_perimeter
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) compute_perimeterf2pywrap
      compute_perimeterf2pywrap = compute_perimeter(v1, v2)
      end subroutine f2pywrap_second_order_centering_compute_perimeter
      subroutine f2pywrap_second_order_centering_cryst_to_cart (cryst_to&
     &_cartf2pywrap, v, alat)
      use second_order_centering, only : cryst_to_cart
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      cryst_to_cartf2pywrap = cryst_to_cart(v, alat)
      end subroutine f2pywrap_second_order_centering_cryst_to_cart
      
      subroutine f2pyinitsecond_order_centering(f2pysetupfunc)
      use second_order_centering, only : analysis
      use second_order_centering, only : center
      interface 
      subroutine f2pywrap_second_order_centering_within_dmax (within_dma&
     &xf2pywrap, v1, v2, d1, d2, tol)
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical within_dmaxf2pywrap
      end subroutine f2pywrap_second_order_centering_within_dmax 
      subroutine f2pywrap_second_order_centering_compute_perimeter (comp&
     &ute_perimeterf2pywrap, v1, v2)
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) compute_perimeterf2pywrap
      end subroutine f2pywrap_second_order_centering_compute_perimeter 
      subroutine f2pywrap_second_order_centering_cryst_to_cart (cryst_to&
     &_cartf2pywrap, v, alat)
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      end subroutine f2pywrap_second_order_centering_cryst_to_cart
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(analysis,center,f2pywrap_second_order_centering&
     &_within_dmax,f2pywrap_second_order_centering_compute_perimeter,f2p&
     &ywrap_second_order_centering_cryst_to_cart)
      end subroutine f2pyinitsecond_order_centering

      subroutine f2py_second_order_asr_getdims_p(r,s,f2pysetdata,flag)
      use second_order_asr, only: d => p

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_second_order_asr_getdims_p
      subroutine f2pywrap_second_order_asr_geq (geqf2pywrap, v1, v2, lat&
     &, pbc, f2py_v1_d0, f2py_v2_d0, f2py_lat_d0)
      use second_order_asr, only : geq
      logical pbc
      integer f2py_v1_d0
      integer f2py_v2_d0
      integer f2py_lat_d0
      integer v1(f2py_v1_d0)
      integer v2(f2py_v2_d0)
      integer lat(f2py_lat_d0)
      logical geqf2pywrap
      geqf2pywrap = .not.(.not.geq(v1, v2, lat, pbc))
      end subroutine f2pywrap_second_order_asr_geq
      
      subroutine f2pyinitsecond_order_asr(f2pysetupfunc)
      use second_order_asr, only : perm_initialized
      use second_order_asr, only : p
      use second_order_asr, only : initialize_perm
      use second_order_asr, only : clear_all
      use second_order_asr, only : impose_perm_sym
      use second_order_asr, only : impose_asr_2nd
      use second_order_asr, only : impose_asr
      interface 
      subroutine f2pywrap_second_order_asr_geq (geqf2pywrap, v1, v2, lat&
     &, pbc, f2py_v1_d0, f2py_v2_d0, f2py_lat_d0)
      logical pbc
      integer f2py_v1_d0
      integer f2py_v2_d0
      integer f2py_lat_d0
      integer v1(f2py_v1_d0)
      integer v2(f2py_v2_d0)
      integer lat(f2py_lat_d0)
      logical geqf2pywrap
      end subroutine f2pywrap_second_order_asr_geq
      end interface
      external f2pysetupfunc
      external f2py_second_order_asr_getdims_p
      call f2pysetupfunc(perm_initialized,f2py_second_order_asr_getdims_&
     &p,initialize_perm,clear_all,f2pywrap_second_order_asr_geq,impose_p&
     &erm_sym,impose_asr_2nd,impose_asr)
      end subroutine f2pyinitsecond_order_asr


