/* File: secondordermodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Sep 12 12:33:34 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *secondorder_error;
static PyObject *secondorder_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(secondorder_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#define CHECKARRAY(check,tcheck,name) \
    if (!(check)) {\
        PyErr_SetString(secondorder_error,"("tcheck") failed for "name);\
        /*goto capi_fail;*/\
    } else 

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = secondorder_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = secondorder_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** analysis **********************************/
static char doc_f2py_rout_secondorder_second_order_centering_analysis[] = "\
weight,xr2 = analysis(far,tol,dmax,sc_size,xr2_list,alat,tau,tensor,[nat,n_blocks])\n\nWrapper for ``analysis``.\
\n\nParameters\n----------\n"
"far : input int\n"
"tol : input float\n"
"dmax : input rank-1 array('d') with bounds (nat)\n"
"sc_size : input rank-1 array('i') with bounds (3)\n"
"xr2_list : input rank-2 array('i') with bounds (3,n_blocks)\n"
"alat : input rank-2 array('d') with bounds (3,3)\n"
"tau : input rank-2 array('d') with bounds (nat,3)\n"
"tensor : input rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(dmax, 0)\n"
"n_blocks : input int, optional\n    Default: shape(xr2_list, 1)\n"
"\nReturns\n-------\n"
"weight : rank-3 array('i') with bounds (nat,nat,n_blocks)\n"
"xr2 : rank-5 array('i') with bounds (3,1 + 4 * far + 4 * far * far,nat,nat,n_blocks)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_centering_analysis(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,int*,int*,double*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int far = 0;
    PyObject *far_capi = Py_None;
    double tol = 0;
    PyObject *tol_capi = Py_None;
    double *dmax = NULL;
    npy_intp dmax_Dims[1] = {-1};
    const int dmax_Rank = 1;
    PyArrayObject *capi_dmax_as_array = NULL;
    int capi_dmax_intent = 0;
    PyObject *dmax_capi = Py_None;
    int *sc_size = NULL;
    npy_intp sc_size_Dims[1] = {-1};
    const int sc_size_Rank = 1;
    PyArrayObject *capi_sc_size_as_array = NULL;
    int capi_sc_size_intent = 0;
    PyObject *sc_size_capi = Py_None;
    int *xr2_list = NULL;
    npy_intp xr2_list_Dims[2] = {-1, -1};
    const int xr2_list_Rank = 2;
    PyArrayObject *capi_xr2_list_as_array = NULL;
    int capi_xr2_list_intent = 0;
    PyObject *xr2_list_capi = Py_None;
    double *alat = NULL;
    npy_intp alat_Dims[2] = {-1, -1};
    const int alat_Rank = 2;
    PyArrayObject *capi_alat_as_array = NULL;
    int capi_alat_intent = 0;
    PyObject *alat_capi = Py_None;
    double *tau = NULL;
    npy_intp tau_Dims[2] = {-1, -1};
    const int tau_Rank = 2;
    PyArrayObject *capi_tau_as_array = NULL;
    int capi_tau_intent = 0;
    PyObject *tau_capi = Py_None;
    double *tensor = NULL;
    npy_intp tensor_Dims[3] = {-1, -1, -1};
    const int tensor_Rank = 3;
    PyArrayObject *capi_tensor_as_array = NULL;
    int capi_tensor_intent = 0;
    PyObject *tensor_capi = Py_None;
    int *weight = NULL;
    npy_intp weight_Dims[3] = {-1, -1, -1};
    const int weight_Rank = 3;
    PyArrayObject *capi_weight_as_array = NULL;
    int capi_weight_intent = 0;
    int *xr2 = NULL;
    npy_intp xr2_Dims[5] = {-1, -1, -1, -1, -1};
    const int xr2_Rank = 5;
    PyArrayObject *capi_xr2_as_array = NULL;
    int capi_xr2_intent = 0;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    static char *capi_kwlist[] = {"far","tol","dmax","sc_size","xr2_list","alat","tau","tensor","nat","n_blocks",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|OO:secondorder.second_order_centering.analysis",\
        capi_kwlist,&far_capi,&tol_capi,&dmax_capi,&sc_size_capi,&xr2_list_capi,&alat_capi,&tau_capi,&tensor_capi,&nat_capi,&n_blocks_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable far */
        f2py_success = int_from_pyobj(&far,far_capi,"secondorder.second_order_centering.analysis() 1st argument (far) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dmax */
    ;
    capi_dmax_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 3rd argument `dmax`";
    capi_dmax_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dmax_Dims,dmax_Rank,  capi_dmax_intent,dmax_capi,capi_errmess);
    if (capi_dmax_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dmax = (double *)(PyArray_DATA(capi_dmax_as_array));

    /* Processing variable alat */
    alat_Dims[0]=3,alat_Dims[1]=3;
    capi_alat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 6th argument `alat`";
    capi_alat_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alat_Dims,alat_Rank,  capi_alat_intent,alat_capi,capi_errmess);
    if (capi_alat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alat = (double *)(PyArray_DATA(capi_alat_as_array));

    /* Processing variable xr2_list */
    xr2_list_Dims[0]=3;
    capi_xr2_list_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 5th argument `xr2_list`";
    capi_xr2_list_as_array = ndarray_from_pyobj(  NPY_INT,1,xr2_list_Dims,xr2_list_Rank,  capi_xr2_list_intent,xr2_list_capi,capi_errmess);
    if (capi_xr2_list_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xr2_list = (int *)(PyArray_DATA(capi_xr2_list_as_array));

    /* Processing variable tol */
        f2py_success = double_from_pyobj(&tol,tol_capi,"secondorder.second_order_centering.analysis() 2nd argument (tol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable sc_size */
    sc_size_Dims[0]=3;
    capi_sc_size_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 4th argument `sc_size`";
    capi_sc_size_as_array = ndarray_from_pyobj(  NPY_INT,1,sc_size_Dims,sc_size_Rank,  capi_sc_size_intent,sc_size_capi,capi_errmess);
    if (capi_sc_size_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sc_size = (int *)(PyArray_DATA(capi_sc_size_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(dmax, 0); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"secondorder.second_order_centering.analysis() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(dmax, 0) == nat,"shape(dmax, 0) == nat","1st keyword nat","analysis:nat=%d",nat) {
    /* Processing variable tau */
    tau_Dims[0]=nat,tau_Dims[1]=3;
    capi_tau_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 7th argument `tau`";
    capi_tau_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,tau_Dims,tau_Rank,  capi_tau_intent,tau_capi,capi_errmess);
    if (capi_tau_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tau = (double *)(PyArray_DATA(capi_tau_as_array));

    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(xr2_list, 1); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_centering.analysis() 2nd keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xr2_list, 1) == n_blocks,"shape(xr2_list, 1) == n_blocks","2nd keyword n_blocks","analysis:n_blocks=%d",n_blocks) {
    /* Processing variable weight */
    weight_Dims[0]=nat,weight_Dims[1]=nat,weight_Dims[2]=n_blocks;
    capi_weight_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the hidden `weight`";
    capi_weight_as_array = ndarray_from_pyobj(  NPY_INT,1,weight_Dims,weight_Rank,  capi_weight_intent,Py_None,capi_errmess);
    if (capi_weight_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        weight = (int *)(PyArray_DATA(capi_weight_as_array));

    /* Processing variable xr2 */
    xr2_Dims[0]=3,xr2_Dims[1]=1 + 4 * far + 4 * far * far,xr2_Dims[2]=nat,xr2_Dims[3]=nat,xr2_Dims[4]=n_blocks;
    capi_xr2_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the hidden `xr2`";
    capi_xr2_as_array = ndarray_from_pyobj(  NPY_INT,1,xr2_Dims,xr2_Rank,  capi_xr2_intent,Py_None,capi_errmess);
    if (capi_xr2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xr2 = (int *)(PyArray_DATA(capi_xr2_as_array));

    /* Processing variable tensor */
    tensor_Dims[0]=3 * nat,tensor_Dims[1]=3 * nat,tensor_Dims[2]=n_blocks;
    capi_tensor_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.analysis: failed to create array from the 8th argument `tensor`";
    capi_tensor_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,tensor_Dims,tensor_Rank,  capi_tensor_intent,tensor_capi,capi_errmess);
    if (capi_tensor_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tensor = (double *)(PyArray_DATA(capi_tensor_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&far,&tol,dmax,sc_size,xr2_list,alat,tau,tensor,weight,xr2,&nat,&n_blocks);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_weight_as_array,capi_xr2_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_tensor_as_array!=tensor_capi) {
        Py_XDECREF(capi_tensor_as_array); }
    }  /* if (capi_tensor_as_array == NULL) ... else of tensor */
    /* End of cleaning variable tensor */
    }  /* if (capi_xr2_as_array == NULL) ... else of xr2 */
    /* End of cleaning variable xr2 */
    }  /* if (capi_weight_as_array == NULL) ... else of weight */
    /* End of cleaning variable weight */
    } /*CHECKSCALAR(shape(xr2_list, 1) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    if((PyObject *)capi_tau_as_array!=tau_capi) {
        Py_XDECREF(capi_tau_as_array); }
    }  /* if (capi_tau_as_array == NULL) ... else of tau */
    /* End of cleaning variable tau */
    } /*CHECKSCALAR(shape(dmax, 0) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_sc_size_as_array!=sc_size_capi) {
        Py_XDECREF(capi_sc_size_as_array); }
    }  /* if (capi_sc_size_as_array == NULL) ... else of sc_size */
    /* End of cleaning variable sc_size */
    } /*if (f2py_success) of tol*/
    /* End of cleaning variable tol */
    if((PyObject *)capi_xr2_list_as_array!=xr2_list_capi) {
        Py_XDECREF(capi_xr2_list_as_array); }
    }  /* if (capi_xr2_list_as_array == NULL) ... else of xr2_list */
    /* End of cleaning variable xr2_list */
    if((PyObject *)capi_alat_as_array!=alat_capi) {
        Py_XDECREF(capi_alat_as_array); }
    }  /* if (capi_alat_as_array == NULL) ... else of alat */
    /* End of cleaning variable alat */
    if((PyObject *)capi_dmax_as_array!=dmax_capi) {
        Py_XDECREF(capi_dmax_as_array); }
    }  /* if (capi_dmax_as_array == NULL) ... else of dmax */
    /* End of cleaning variable dmax */
    } /*if (f2py_success) of far*/
    /* End of cleaning variable far */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of analysis ******************************/

/*********************************** center ***********************************/
static char doc_f2py_rout_secondorder_second_order_centering_center[] = "\
centered = center(original,weight,xr2_list,xr2,far,[nat,n_blocks,n_blocks_old])\n\nWrapper for ``center``.\
\n\nParameters\n----------\n"
"original : input rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks_old)\n"
"weight : input rank-3 array('i') with bounds (nat,nat,n_blocks_old)\n"
"xr2_list : input rank-2 array('i') with bounds (3,n_blocks)\n"
"xr2 : input rank-5 array('i') with bounds (3,1 + 4 * far + 4 * far * far,nat,nat,n_blocks_old)\n"
"far : input int\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(original, 0) / 3\n"
"n_blocks : input int, optional\n    Default: shape(xr2_list, 1)\n"
"n_blocks_old : input int, optional\n    Default: shape(original, 2)\n"
"\nReturns\n-------\n"
"centered : rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_centering_center(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *original = NULL;
    npy_intp original_Dims[3] = {-1, -1, -1};
    const int original_Rank = 3;
    PyArrayObject *capi_original_as_array = NULL;
    int capi_original_intent = 0;
    PyObject *original_capi = Py_None;
    int *weight = NULL;
    npy_intp weight_Dims[3] = {-1, -1, -1};
    const int weight_Rank = 3;
    PyArrayObject *capi_weight_as_array = NULL;
    int capi_weight_intent = 0;
    PyObject *weight_capi = Py_None;
    int *xr2_list = NULL;
    npy_intp xr2_list_Dims[2] = {-1, -1};
    const int xr2_list_Rank = 2;
    PyArrayObject *capi_xr2_list_as_array = NULL;
    int capi_xr2_list_intent = 0;
    PyObject *xr2_list_capi = Py_None;
    int *xr2 = NULL;
    npy_intp xr2_Dims[5] = {-1, -1, -1, -1, -1};
    const int xr2_Rank = 5;
    PyArrayObject *capi_xr2_as_array = NULL;
    int capi_xr2_intent = 0;
    PyObject *xr2_capi = Py_None;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    double *centered = NULL;
    npy_intp centered_Dims[3] = {-1, -1, -1};
    const int centered_Rank = 3;
    PyArrayObject *capi_centered_as_array = NULL;
    int capi_centered_intent = 0;
    int far = 0;
    PyObject *far_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    int n_blocks_old = 0;
    PyObject *n_blocks_old_capi = Py_None;
    static char *capi_kwlist[] = {"original","weight","xr2_list","xr2","far","nat","n_blocks","n_blocks_old",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|OOO:secondorder.second_order_centering.center",\
        capi_kwlist,&original_capi,&weight_capi,&xr2_list_capi,&xr2_capi,&far_capi,&nat_capi,&n_blocks_capi,&n_blocks_old_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable far */
        f2py_success = int_from_pyobj(&far,far_capi,"secondorder.second_order_centering.center() 5th argument (far) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xr2_list */
    xr2_list_Dims[0]=3;
    capi_xr2_list_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.center: failed to create array from the 3rd argument `xr2_list`";
    capi_xr2_list_as_array = ndarray_from_pyobj(  NPY_INT,1,xr2_list_Dims,xr2_list_Rank,  capi_xr2_list_intent,xr2_list_capi,capi_errmess);
    if (capi_xr2_list_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xr2_list = (int *)(PyArray_DATA(capi_xr2_list_as_array));

    /* Processing variable original */
    ;
    capi_original_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.center: failed to create array from the 1st argument `original`";
    capi_original_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,original_Dims,original_Rank,  capi_original_intent,original_capi,capi_errmess);
    if (capi_original_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        original = (double *)(PyArray_DATA(capi_original_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(original, 0) / 3; else
        f2py_success = int_from_pyobj(&nat,nat_capi,"secondorder.second_order_centering.center() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(original, 0) == 3 * nat,"shape(original, 0) == 3 * nat","1st keyword nat","center:nat=%d",nat) {
    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(xr2_list, 1); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_centering.center() 2nd keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xr2_list, 1) == n_blocks,"shape(xr2_list, 1) == n_blocks","2nd keyword n_blocks","center:n_blocks=%d",n_blocks) {
    /* Processing variable n_blocks_old */
    if (n_blocks_old_capi == Py_None) n_blocks_old = shape(original, 2); else
        f2py_success = int_from_pyobj(&n_blocks_old,n_blocks_old_capi,"secondorder.second_order_centering.center() 3rd keyword (n_blocks_old) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(original, 2) == n_blocks_old,"shape(original, 2) == n_blocks_old","3rd keyword n_blocks_old","center:n_blocks_old=%d",n_blocks_old) {
    /* Processing variable centered */
    centered_Dims[0]=3 * nat,centered_Dims[1]=3 * nat,centered_Dims[2]=n_blocks;
    capi_centered_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.center: failed to create array from the hidden `centered`";
    capi_centered_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,centered_Dims,centered_Rank,  capi_centered_intent,Py_None,capi_errmess);
    if (capi_centered_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        centered = (double *)(PyArray_DATA(capi_centered_as_array));

    /* Processing variable xr2 */
    xr2_Dims[0]=3,xr2_Dims[1]=1 + 4 * far + 4 * far * far,xr2_Dims[2]=nat,xr2_Dims[3]=nat,xr2_Dims[4]=n_blocks_old;
    capi_xr2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.center: failed to create array from the 4th argument `xr2`";
    capi_xr2_as_array = ndarray_from_pyobj(  NPY_INT,1,xr2_Dims,xr2_Rank,  capi_xr2_intent,xr2_capi,capi_errmess);
    if (capi_xr2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xr2 = (int *)(PyArray_DATA(capi_xr2_as_array));

    CHECKARRAY(shape(xr2, 1) == 1 + 4 * far + 4 * far * far,"shape(xr2, 1) == 1 + 4 * far + 4 * far * far","4th argument xr2") {
    /* Processing variable weight */
    weight_Dims[0]=nat,weight_Dims[1]=nat,weight_Dims[2]=n_blocks_old;
    capi_weight_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.center: failed to create array from the 2nd argument `weight`";
    capi_weight_as_array = ndarray_from_pyobj(  NPY_INT,1,weight_Dims,weight_Rank,  capi_weight_intent,weight_capi,capi_errmess);
    if (capi_weight_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        weight = (int *)(PyArray_DATA(capi_weight_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(original,weight,xr2_list,xr2,&nat,centered,&far,&n_blocks,&n_blocks_old);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_centered_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_weight_as_array!=weight_capi) {
        Py_XDECREF(capi_weight_as_array); }
    }  /* if (capi_weight_as_array == NULL) ... else of weight */
    /* End of cleaning variable weight */
    } /*CHECKARRAY(shape(xr2, 1) == 1 + 4 * far + 4 * far * far)*/
    if((PyObject *)capi_xr2_as_array!=xr2_capi) {
        Py_XDECREF(capi_xr2_as_array); }
    }  /* if (capi_xr2_as_array == NULL) ... else of xr2 */
    /* End of cleaning variable xr2 */
    }  /* if (capi_centered_as_array == NULL) ... else of centered */
    /* End of cleaning variable centered */
    } /*CHECKSCALAR(shape(original, 2) == n_blocks_old)*/
    } /*if (f2py_success) of n_blocks_old*/
    /* End of cleaning variable n_blocks_old */
    } /*CHECKSCALAR(shape(xr2_list, 1) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    } /*CHECKSCALAR(shape(original, 0) == 3 * nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_original_as_array!=original_capi) {
        Py_XDECREF(capi_original_as_array); }
    }  /* if (capi_original_as_array == NULL) ... else of original */
    /* End of cleaning variable original */
    if((PyObject *)capi_xr2_list_as_array!=xr2_list_capi) {
        Py_XDECREF(capi_xr2_list_as_array); }
    }  /* if (capi_xr2_list_as_array == NULL) ... else of xr2_list */
    /* End of cleaning variable xr2_list */
    } /*if (f2py_success) of far*/
    /* End of cleaning variable far */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of center *******************************/

/******************************** within_dmax ********************************/
static char doc_f2py_rout_secondorder_second_order_centering_within_dmax[] = "\
within_dmax = within_dmax(v1,v2,d1,d2,tol)\n\nWrapper for ``within_dmax``.\
\n\nParameters\n----------\n"
"v1 : input rank-1 array('d') with bounds (3)\n"
"v2 : input rank-1 array('d') with bounds (3)\n"
"d1 : input float\n"
"d2 : input float\n"
"tol : input float\n"
"\nReturns\n-------\n"
"within_dmax : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_secondorder_second_order_centering_within_dmax(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int within_dmaxf2pywrap = 0;
    double *v1 = NULL;
    npy_intp v1_Dims[1] = {-1};
    const int v1_Rank = 1;
    PyArrayObject *capi_v1_as_array = NULL;
    int capi_v1_intent = 0;
    PyObject *v1_capi = Py_None;
    double *v2 = NULL;
    npy_intp v2_Dims[1] = {-1};
    const int v2_Rank = 1;
    PyArrayObject *capi_v2_as_array = NULL;
    int capi_v2_intent = 0;
    PyObject *v2_capi = Py_None;
    double d1 = 0;
    PyObject *d1_capi = Py_None;
    double d2 = 0;
    PyObject *d2_capi = Py_None;
    double tol = 0;
    PyObject *tol_capi = Py_None;
    static char *capi_kwlist[] = {"v1","v2","d1","d2","tol",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:secondorder.second_order_centering.within_dmax",\
        capi_kwlist,&v1_capi,&v2_capi,&d1_capi,&d2_capi,&tol_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable v1 */
    v1_Dims[0]=3;
    capi_v1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.within_dmax: failed to create array from the 1st argument `v1`";
    capi_v1_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,v1_Dims,v1_Rank,  capi_v1_intent,v1_capi,capi_errmess);
    if (capi_v1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v1 = (double *)(PyArray_DATA(capi_v1_as_array));

    /* Processing variable v2 */
    v2_Dims[0]=3;
    capi_v2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.within_dmax: failed to create array from the 2nd argument `v2`";
    capi_v2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,v2_Dims,v2_Rank,  capi_v2_intent,v2_capi,capi_errmess);
    if (capi_v2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v2 = (double *)(PyArray_DATA(capi_v2_as_array));

    /* Processing variable d1 */
        f2py_success = double_from_pyobj(&d1,d1_capi,"secondorder.second_order_centering.within_dmax() 3rd argument (d1) can't be converted to double");
    if (f2py_success) {
    /* Processing variable d2 */
        f2py_success = double_from_pyobj(&d2,d2_capi,"secondorder.second_order_centering.within_dmax() 4th argument (d2) can't be converted to double");
    if (f2py_success) {
    /* Processing variable tol */
        f2py_success = double_from_pyobj(&tol,tol_capi,"secondorder.second_order_centering.within_dmax() 5th argument (tol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable within_dmaxf2pywrap */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&within_dmaxf2pywrap,v1,v2,&d1,&d2,&tol);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",within_dmaxf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable within_dmaxf2pywrap */
    } /*if (f2py_success) of tol*/
    /* End of cleaning variable tol */
    } /*if (f2py_success) of d2*/
    /* End of cleaning variable d2 */
    } /*if (f2py_success) of d1*/
    /* End of cleaning variable d1 */
    if((PyObject *)capi_v2_as_array!=v2_capi) {
        Py_XDECREF(capi_v2_as_array); }
    }  /* if (capi_v2_as_array == NULL) ... else of v2 */
    /* End of cleaning variable v2 */
    if((PyObject *)capi_v1_as_array!=v1_capi) {
        Py_XDECREF(capi_v1_as_array); }
    }  /* if (capi_v1_as_array == NULL) ... else of v1 */
    /* End of cleaning variable v1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of within_dmax *****************************/

/***************************** compute_perimeter *****************************/
static char doc_f2py_rout_secondorder_second_order_centering_compute_perimeter[] = "\
compute_perimeter = compute_perimeter(v1,v2)\n\nWrapper for ``compute_perimeter``.\
\n\nParameters\n----------\n"
"v1 : input rank-1 array('d') with bounds (3)\n"
"v2 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"compute_perimeter : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_secondorder_second_order_centering_compute_perimeter(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double compute_perimeterf2pywrap = 0;
    double *v1 = NULL;
    npy_intp v1_Dims[1] = {-1};
    const int v1_Rank = 1;
    PyArrayObject *capi_v1_as_array = NULL;
    int capi_v1_intent = 0;
    PyObject *v1_capi = Py_None;
    double *v2 = NULL;
    npy_intp v2_Dims[1] = {-1};
    const int v2_Rank = 1;
    PyArrayObject *capi_v2_as_array = NULL;
    int capi_v2_intent = 0;
    PyObject *v2_capi = Py_None;
    static char *capi_kwlist[] = {"v1","v2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:secondorder.second_order_centering.compute_perimeter",\
        capi_kwlist,&v1_capi,&v2_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable v1 */
    v1_Dims[0]=3;
    capi_v1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.compute_perimeter: failed to create array from the 1st argument `v1`";
    capi_v1_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,v1_Dims,v1_Rank,  capi_v1_intent,v1_capi,capi_errmess);
    if (capi_v1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v1 = (double *)(PyArray_DATA(capi_v1_as_array));

    /* Processing variable v2 */
    v2_Dims[0]=3;
    capi_v2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.compute_perimeter: failed to create array from the 2nd argument `v2`";
    capi_v2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,v2_Dims,v2_Rank,  capi_v2_intent,v2_capi,capi_errmess);
    if (capi_v2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v2 = (double *)(PyArray_DATA(capi_v2_as_array));

    /* Processing variable compute_perimeterf2pywrap */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&compute_perimeterf2pywrap,v1,v2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",compute_perimeterf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable compute_perimeterf2pywrap */
    if((PyObject *)capi_v2_as_array!=v2_capi) {
        Py_XDECREF(capi_v2_as_array); }
    }  /* if (capi_v2_as_array == NULL) ... else of v2 */
    /* End of cleaning variable v2 */
    if((PyObject *)capi_v1_as_array!=v1_capi) {
        Py_XDECREF(capi_v1_as_array); }
    }  /* if (capi_v1_as_array == NULL) ... else of v1 */
    /* End of cleaning variable v1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of compute_perimeter **************************/

/******************************* cryst_to_cart *******************************/
static char doc_f2py_rout_secondorder_second_order_centering_cryst_to_cart[] = "\
cryst_to_cart = cryst_to_cart(v,alat)\n\nWrapper for ``cryst_to_cart``.\
\n\nParameters\n----------\n"
"v : input rank-1 array('i') with bounds (3)\n"
"alat : input rank-2 array('d') with bounds (3,3)\n"
"\nReturns\n-------\n"
"cryst_to_cart : rank-1 array('d') with bounds (3) and cryst_to_cartf2pywrap storage";
/* #declfortranroutine# */
static PyObject *f2py_rout_secondorder_second_order_centering_cryst_to_cart(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *cryst_to_cartf2pywrap = NULL;
    npy_intp cryst_to_cartf2pywrap_Dims[1] = {-1};
    const int cryst_to_cartf2pywrap_Rank = 1;
    PyArrayObject *capi_cryst_to_cartf2pywrap_as_array = NULL;
    int capi_cryst_to_cartf2pywrap_intent = 0;
    int *v = NULL;
    npy_intp v_Dims[1] = {-1};
    const int v_Rank = 1;
    PyArrayObject *capi_v_as_array = NULL;
    int capi_v_intent = 0;
    PyObject *v_capi = Py_None;
    double *alat = NULL;
    npy_intp alat_Dims[2] = {-1, -1};
    const int alat_Rank = 2;
    PyArrayObject *capi_alat_as_array = NULL;
    int capi_alat_intent = 0;
    PyObject *alat_capi = Py_None;
    static char *capi_kwlist[] = {"v","alat",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:secondorder.second_order_centering.cryst_to_cart",\
        capi_kwlist,&v_capi,&alat_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable v */
    v_Dims[0]=3;
    capi_v_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.cryst_to_cart: failed to create array from the 1st argument `v`";
    capi_v_as_array = ndarray_from_pyobj(  NPY_INT,1,v_Dims,v_Rank,  capi_v_intent,v_capi,capi_errmess);
    if (capi_v_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v = (int *)(PyArray_DATA(capi_v_as_array));

    /* Processing variable alat */
    alat_Dims[0]=3,alat_Dims[1]=3;
    capi_alat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.cryst_to_cart: failed to create array from the 2nd argument `alat`";
    capi_alat_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alat_Dims,alat_Rank,  capi_alat_intent,alat_capi,capi_errmess);
    if (capi_alat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alat = (double *)(PyArray_DATA(capi_alat_as_array));

    /* Processing variable cryst_to_cartf2pywrap */
    cryst_to_cartf2pywrap_Dims[0]=3;
    capi_cryst_to_cartf2pywrap_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_centering.cryst_to_cart: failed to create array from the hidden `cryst_to_cartf2pywrap`";
    capi_cryst_to_cartf2pywrap_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cryst_to_cartf2pywrap_Dims,cryst_to_cartf2pywrap_Rank,  capi_cryst_to_cartf2pywrap_intent,Py_None,capi_errmess);
    if (capi_cryst_to_cartf2pywrap_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cryst_to_cartf2pywrap = (double *)(PyArray_DATA(capi_cryst_to_cartf2pywrap_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(cryst_to_cartf2pywrap,v,alat);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_cryst_to_cartf2pywrap_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_cryst_to_cartf2pywrap_as_array == NULL) ... else of cryst_to_cartf2pywrap */
    /* End of cleaning variable cryst_to_cartf2pywrap */
    if((PyObject *)capi_alat_as_array!=alat_capi) {
        Py_XDECREF(capi_alat_as_array); }
    }  /* if (capi_alat_as_array == NULL) ... else of alat */
    /* End of cleaning variable alat */
    if((PyObject *)capi_v_as_array!=v_capi) {
        Py_XDECREF(capi_v_as_array); }
    }  /* if (capi_v_as_array == NULL) ... else of v */
    /* End of cleaning variable v */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of cryst_to_cart ****************************/

/****************************** initialize_perm ******************************/
static char doc_f2py_rout_secondorder_second_order_asr_initialize_perm[] = "\
initialize_perm(r2,sclat,pbc,[n_blocks])\n\nWrapper for ``initialize_perm``.\
\n\nParameters\n----------\n"
"r2 : input rank-2 array('i') with bounds (3,n_blocks)\n"
"sclat : input rank-1 array('i') with bounds (3)\n"
"pbc : input int\n"
"\nOther Parameters\n----------------\n"
"n_blocks : input int, optional\n    Default: shape(r2, 1)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_asr_initialize_perm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *r2 = NULL;
    npy_intp r2_Dims[2] = {-1, -1};
    const int r2_Rank = 2;
    PyArrayObject *capi_r2_as_array = NULL;
    int capi_r2_intent = 0;
    PyObject *r2_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    int *sclat = NULL;
    npy_intp sclat_Dims[1] = {-1};
    const int sclat_Rank = 1;
    PyArrayObject *capi_sclat_as_array = NULL;
    int capi_sclat_intent = 0;
    PyObject *sclat_capi = Py_None;
    int pbc = 0;
    PyObject *pbc_capi = Py_None;
    static char *capi_kwlist[] = {"r2","sclat","pbc","n_blocks",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:secondorder.second_order_asr.initialize_perm",\
        capi_kwlist,&r2_capi,&sclat_capi,&pbc_capi,&n_blocks_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable r2 */
    r2_Dims[0]=3;
    capi_r2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.initialize_perm: failed to create array from the 1st argument `r2`";
    capi_r2_as_array = ndarray_from_pyobj(  NPY_INT,1,r2_Dims,r2_Rank,  capi_r2_intent,r2_capi,capi_errmess);
    if (capi_r2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        r2 = (int *)(PyArray_DATA(capi_r2_as_array));

    /* Processing variable sclat */
    sclat_Dims[0]=3;
    capi_sclat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.initialize_perm: failed to create array from the 2nd argument `sclat`";
    capi_sclat_as_array = ndarray_from_pyobj(  NPY_INT,1,sclat_Dims,sclat_Rank,  capi_sclat_intent,sclat_capi,capi_errmess);
    if (capi_sclat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sclat = (int *)(PyArray_DATA(capi_sclat_as_array));

    /* Processing variable pbc */
        pbc = (int)PyObject_IsTrue(pbc_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(r2, 1); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_asr.initialize_perm() 1st keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(r2, 1) == n_blocks,"shape(r2, 1) == n_blocks","1st keyword n_blocks","initialize_perm:n_blocks=%d",n_blocks) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(r2,&n_blocks,sclat,&pbc);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(r2, 1) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    } /*if (f2py_success) of pbc*/
    /* End of cleaning variable pbc */
    if((PyObject *)capi_sclat_as_array!=sclat_capi) {
        Py_XDECREF(capi_sclat_as_array); }
    }  /* if (capi_sclat_as_array == NULL) ... else of sclat */
    /* End of cleaning variable sclat */
    if((PyObject *)capi_r2_as_array!=r2_capi) {
        Py_XDECREF(capi_r2_as_array); }
    }  /* if (capi_r2_as_array == NULL) ... else of r2 */
    /* End of cleaning variable r2 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of initialize_perm ***************************/

/********************************* clear_all *********************************/
static char doc_f2py_rout_secondorder_second_order_asr_clear_all[] = "\
clear_all()\n\nWrapper for ``clear_all``.\
\n";
/*  */
static PyObject *f2py_rout_secondorder_second_order_asr_clear_all(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:secondorder.second_order_asr.clear_all",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of clear_all ******************************/

/************************************ geq ************************************/
static char doc_f2py_rout_secondorder_second_order_asr_geq[] = "\
geq = geq(v1,v2,lat,pbc)\n\nWrapper for ``geq``.\
\n\nParameters\n----------\n"
"v1 : input rank-1 array('i') with bounds (f2py_v1_d0)\n"
"v2 : input rank-1 array('i') with bounds (f2py_v2_d0)\n"
"lat : input rank-1 array('i') with bounds (f2py_lat_d0)\n"
"pbc : input int\n"
"\nReturns\n-------\n"
"geq : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_secondorder_second_order_asr_geq(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int geqf2pywrap = 0;
    int *v1 = NULL;
    npy_intp v1_Dims[1] = {-1};
    const int v1_Rank = 1;
    PyArrayObject *capi_v1_as_array = NULL;
    int capi_v1_intent = 0;
    PyObject *v1_capi = Py_None;
    int *v2 = NULL;
    npy_intp v2_Dims[1] = {-1};
    const int v2_Rank = 1;
    PyArrayObject *capi_v2_as_array = NULL;
    int capi_v2_intent = 0;
    PyObject *v2_capi = Py_None;
    int *lat = NULL;
    npy_intp lat_Dims[1] = {-1};
    const int lat_Rank = 1;
    PyArrayObject *capi_lat_as_array = NULL;
    int capi_lat_intent = 0;
    PyObject *lat_capi = Py_None;
    int pbc = 0;
    PyObject *pbc_capi = Py_None;
    int f2py_v1_d0 = 0;
    int f2py_v2_d0 = 0;
    int f2py_lat_d0 = 0;
    static char *capi_kwlist[] = {"v1","v2","lat","pbc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:secondorder.second_order_asr.geq",\
        capi_kwlist,&v1_capi,&v2_capi,&lat_capi,&pbc_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable v1 */
    ;
    capi_v1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.geq: failed to create array from the 1st argument `v1`";
    capi_v1_as_array = ndarray_from_pyobj(  NPY_INT,1,v1_Dims,v1_Rank,  capi_v1_intent,v1_capi,capi_errmess);
    if (capi_v1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v1 = (int *)(PyArray_DATA(capi_v1_as_array));

    /* Processing variable v2 */
    ;
    capi_v2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.geq: failed to create array from the 2nd argument `v2`";
    capi_v2_as_array = ndarray_from_pyobj(  NPY_INT,1,v2_Dims,v2_Rank,  capi_v2_intent,v2_capi,capi_errmess);
    if (capi_v2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        v2 = (int *)(PyArray_DATA(capi_v2_as_array));

    /* Processing variable lat */
    ;
    capi_lat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.geq: failed to create array from the 3rd argument `lat`";
    capi_lat_as_array = ndarray_from_pyobj(  NPY_INT,1,lat_Dims,lat_Rank,  capi_lat_intent,lat_capi,capi_errmess);
    if (capi_lat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        lat = (int *)(PyArray_DATA(capi_lat_as_array));

    /* Processing variable pbc */
        pbc = (int)PyObject_IsTrue(pbc_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable geqf2pywrap */
    /* Processing variable f2py_v1_d0 */
    f2py_v1_d0 = shape(v1, 0);
    /* Processing variable f2py_v2_d0 */
    f2py_v2_d0 = shape(v2, 0);
    /* Processing variable f2py_lat_d0 */
    f2py_lat_d0 = shape(lat, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&geqf2pywrap,v1,v2,lat,&pbc,&f2py_v1_d0,&f2py_v2_d0,&f2py_lat_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",geqf2pywrap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_lat_d0 */
    /* End of cleaning variable f2py_v2_d0 */
    /* End of cleaning variable f2py_v1_d0 */
    /* End of cleaning variable geqf2pywrap */
    } /*if (f2py_success) of pbc*/
    /* End of cleaning variable pbc */
    if((PyObject *)capi_lat_as_array!=lat_capi) {
        Py_XDECREF(capi_lat_as_array); }
    }  /* if (capi_lat_as_array == NULL) ... else of lat */
    /* End of cleaning variable lat */
    if((PyObject *)capi_v2_as_array!=v2_capi) {
        Py_XDECREF(capi_v2_as_array); }
    }  /* if (capi_v2_as_array == NULL) ... else of v2 */
    /* End of cleaning variable v2 */
    if((PyObject *)capi_v1_as_array!=v1_capi) {
        Py_XDECREF(capi_v1_as_array); }
    }  /* if (capi_v1_as_array == NULL) ... else of v1 */
    /* End of cleaning variable v1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************************* end of geq *********************************/

/****************************** impose_perm_sym ******************************/
static char doc_f2py_rout_secondorder_second_order_asr_impose_perm_sym[] = "\
fcvar,fc_sym = impose_perm_sym(fc,r2,sclat,pbc,verbose,[nat,n_blocks])\n\nWrapper for ``impose_perm_sym``.\
\n\nParameters\n----------\n"
"fc : input rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)\n"
"r2 : input rank-2 array('i') with bounds (3,n_blocks)\n"
"sclat : input rank-1 array('i') with bounds (3)\n"
"pbc : input int\n"
"verbose : input int\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(fc, 0) / 3\n"
"n_blocks : input int, optional\n    Default: shape(fc, 2)\n"
"\nReturns\n-------\n"
"fcvar : float\n"
"fc_sym : rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_asr_impose_perm_sym(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *fc = NULL;
    npy_intp fc_Dims[3] = {-1, -1, -1};
    const int fc_Rank = 3;
    PyArrayObject *capi_fc_as_array = NULL;
    int capi_fc_intent = 0;
    PyObject *fc_capi = Py_None;
    int *r2 = NULL;
    npy_intp r2_Dims[2] = {-1, -1};
    const int r2_Rank = 2;
    PyArrayObject *capi_r2_as_array = NULL;
    int capi_r2_intent = 0;
    PyObject *r2_capi = Py_None;
    int *sclat = NULL;
    npy_intp sclat_Dims[1] = {-1};
    const int sclat_Rank = 1;
    PyArrayObject *capi_sclat_as_array = NULL;
    int capi_sclat_intent = 0;
    PyObject *sclat_capi = Py_None;
    int pbc = 0;
    PyObject *pbc_capi = Py_None;
    int verbose = 0;
    PyObject *verbose_capi = Py_None;
    double fcvar = 0;
    double *fc_sym = NULL;
    npy_intp fc_sym_Dims[3] = {-1, -1, -1};
    const int fc_sym_Rank = 3;
    PyArrayObject *capi_fc_sym_as_array = NULL;
    int capi_fc_sym_intent = 0;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    static char *capi_kwlist[] = {"fc","r2","sclat","pbc","verbose","nat","n_blocks",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|OO:secondorder.second_order_asr.impose_perm_sym",\
        capi_kwlist,&fc_capi,&r2_capi,&sclat_capi,&pbc_capi,&verbose_capi,&nat_capi,&n_blocks_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable fc */
    ;
    capi_fc_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_perm_sym: failed to create array from the 1st argument `fc`";
    capi_fc_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_Dims,fc_Rank,  capi_fc_intent,fc_capi,capi_errmess);
    if (capi_fc_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc = (double *)(PyArray_DATA(capi_fc_as_array));

    /* Processing variable sclat */
    sclat_Dims[0]=3;
    capi_sclat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_perm_sym: failed to create array from the 3rd argument `sclat`";
    capi_sclat_as_array = ndarray_from_pyobj(  NPY_INT,1,sclat_Dims,sclat_Rank,  capi_sclat_intent,sclat_capi,capi_errmess);
    if (capi_sclat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sclat = (int *)(PyArray_DATA(capi_sclat_as_array));

    /* Processing variable pbc */
        pbc = (int)PyObject_IsTrue(pbc_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable verbose */
        verbose = (int)PyObject_IsTrue(verbose_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable fcvar */
    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(fc, 0) / 3; else
        f2py_success = int_from_pyobj(&nat,nat_capi,"secondorder.second_order_asr.impose_perm_sym() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 0) == 3 * nat,"shape(fc, 0) == 3 * nat","1st keyword nat","impose_perm_sym:nat=%d",nat) {
    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(fc, 2); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_asr.impose_perm_sym() 2nd keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 2) == n_blocks,"shape(fc, 2) == n_blocks","2nd keyword n_blocks","impose_perm_sym:n_blocks=%d",n_blocks) {
    /* Processing variable r2 */
    r2_Dims[0]=3,r2_Dims[1]=n_blocks;
    capi_r2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_perm_sym: failed to create array from the 2nd argument `r2`";
    capi_r2_as_array = ndarray_from_pyobj(  NPY_INT,1,r2_Dims,r2_Rank,  capi_r2_intent,r2_capi,capi_errmess);
    if (capi_r2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        r2 = (int *)(PyArray_DATA(capi_r2_as_array));

    /* Processing variable fc_sym */
    fc_sym_Dims[0]=3 * nat,fc_sym_Dims[1]=3 * nat,fc_sym_Dims[2]=n_blocks;
    capi_fc_sym_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_perm_sym: failed to create array from the hidden `fc_sym`";
    capi_fc_sym_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_sym_Dims,fc_sym_Rank,  capi_fc_sym_intent,Py_None,capi_errmess);
    if (capi_fc_sym_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc_sym = (double *)(PyArray_DATA(capi_fc_sym_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(fc,r2,sclat,&pbc,&verbose,&fcvar,fc_sym,&nat,&n_blocks);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("dN",fcvar,capi_fc_sym_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_fc_sym_as_array == NULL) ... else of fc_sym */
    /* End of cleaning variable fc_sym */
    if((PyObject *)capi_r2_as_array!=r2_capi) {
        Py_XDECREF(capi_r2_as_array); }
    }  /* if (capi_r2_as_array == NULL) ... else of r2 */
    /* End of cleaning variable r2 */
    } /*CHECKSCALAR(shape(fc, 2) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    } /*CHECKSCALAR(shape(fc, 0) == 3 * nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    /* End of cleaning variable fcvar */
    } /*if (f2py_success) of verbose*/
    /* End of cleaning variable verbose */
    } /*if (f2py_success) of pbc*/
    /* End of cleaning variable pbc */
    if((PyObject *)capi_sclat_as_array!=sclat_capi) {
        Py_XDECREF(capi_sclat_as_array); }
    }  /* if (capi_sclat_as_array == NULL) ... else of sclat */
    /* End of cleaning variable sclat */
    if((PyObject *)capi_fc_as_array!=fc_capi) {
        Py_XDECREF(capi_fc_as_array); }
    }  /* if (capi_fc_as_array == NULL) ... else of fc */
    /* End of cleaning variable fc */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of impose_perm_sym ***************************/

/******************************* impose_asr_2nd *******************************/
static char doc_f2py_rout_secondorder_second_order_asr_impose_asr_2nd[] = "\
fcvar,sum2nd,fc_asr = impose_asr_2nd(fc,pow,sclat,pbc,verbose,[nat,n_blocks])\n\nWrapper for ``impose_asr_2nd``.\
\n\nParameters\n----------\n"
"fc : input rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)\n"
"pow : input float\n"
"sclat : input rank-1 array('i') with bounds (3)\n"
"pbc : input int\n"
"verbose : input int\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(fc, 0) / 3\n"
"n_blocks : input int, optional\n    Default: shape(fc, 2)\n"
"\nReturns\n-------\n"
"fcvar : float\n"
"sum2nd : float\n"
"fc_asr : rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_asr_impose_asr_2nd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*,double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *fc = NULL;
    npy_intp fc_Dims[3] = {-1, -1, -1};
    const int fc_Rank = 3;
    PyArrayObject *capi_fc_as_array = NULL;
    int capi_fc_intent = 0;
    PyObject *fc_capi = Py_None;
    double pow = 0;
    PyObject *pow_capi = Py_None;
    int *sclat = NULL;
    npy_intp sclat_Dims[1] = {-1};
    const int sclat_Rank = 1;
    PyArrayObject *capi_sclat_as_array = NULL;
    int capi_sclat_intent = 0;
    PyObject *sclat_capi = Py_None;
    int pbc = 0;
    PyObject *pbc_capi = Py_None;
    int verbose = 0;
    PyObject *verbose_capi = Py_None;
    double fcvar = 0;
    double sum2nd = 0;
    double *fc_asr = NULL;
    npy_intp fc_asr_Dims[3] = {-1, -1, -1};
    const int fc_asr_Rank = 3;
    PyArrayObject *capi_fc_asr_as_array = NULL;
    int capi_fc_asr_intent = 0;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    static char *capi_kwlist[] = {"fc","pow","sclat","pbc","verbose","nat","n_blocks",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|OO:secondorder.second_order_asr.impose_asr_2nd",\
        capi_kwlist,&fc_capi,&pow_capi,&sclat_capi,&pbc_capi,&verbose_capi,&nat_capi,&n_blocks_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable fc */
    ;
    capi_fc_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr_2nd: failed to create array from the 1st argument `fc`";
    capi_fc_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_Dims,fc_Rank,  capi_fc_intent,fc_capi,capi_errmess);
    if (capi_fc_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc = (double *)(PyArray_DATA(capi_fc_as_array));

    /* Processing variable pow */
        f2py_success = double_from_pyobj(&pow,pow_capi,"secondorder.second_order_asr.impose_asr_2nd() 2nd argument (pow) can't be converted to double");
    if (f2py_success) {
    /* Processing variable sclat */
    sclat_Dims[0]=3;
    capi_sclat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr_2nd: failed to create array from the 3rd argument `sclat`";
    capi_sclat_as_array = ndarray_from_pyobj(  NPY_INT,1,sclat_Dims,sclat_Rank,  capi_sclat_intent,sclat_capi,capi_errmess);
    if (capi_sclat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sclat = (int *)(PyArray_DATA(capi_sclat_as_array));

    /* Processing variable pbc */
        pbc = (int)PyObject_IsTrue(pbc_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable verbose */
        verbose = (int)PyObject_IsTrue(verbose_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable fcvar */
    /* Processing variable sum2nd */
    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(fc, 0) / 3; else
        f2py_success = int_from_pyobj(&nat,nat_capi,"secondorder.second_order_asr.impose_asr_2nd() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 0) == 3 * nat,"shape(fc, 0) == 3 * nat","1st keyword nat","impose_asr_2nd:nat=%d",nat) {
    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(fc, 2); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_asr.impose_asr_2nd() 2nd keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 2) == n_blocks,"shape(fc, 2) == n_blocks","2nd keyword n_blocks","impose_asr_2nd:n_blocks=%d",n_blocks) {
    /* Processing variable fc_asr */
    fc_asr_Dims[0]=3 * nat,fc_asr_Dims[1]=3 * nat,fc_asr_Dims[2]=n_blocks;
    capi_fc_asr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr_2nd: failed to create array from the hidden `fc_asr`";
    capi_fc_asr_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_asr_Dims,fc_asr_Rank,  capi_fc_asr_intent,Py_None,capi_errmess);
    if (capi_fc_asr_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc_asr = (double *)(PyArray_DATA(capi_fc_asr_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(fc,&pow,sclat,&pbc,&verbose,&fcvar,&sum2nd,fc_asr,&nat,&n_blocks);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ddN",fcvar,sum2nd,capi_fc_asr_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_fc_asr_as_array == NULL) ... else of fc_asr */
    /* End of cleaning variable fc_asr */
    } /*CHECKSCALAR(shape(fc, 2) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    } /*CHECKSCALAR(shape(fc, 0) == 3 * nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    /* End of cleaning variable sum2nd */
    /* End of cleaning variable fcvar */
    } /*if (f2py_success) of verbose*/
    /* End of cleaning variable verbose */
    } /*if (f2py_success) of pbc*/
    /* End of cleaning variable pbc */
    if((PyObject *)capi_sclat_as_array!=sclat_capi) {
        Py_XDECREF(capi_sclat_as_array); }
    }  /* if (capi_sclat_as_array == NULL) ... else of sclat */
    /* End of cleaning variable sclat */
    } /*if (f2py_success) of pow*/
    /* End of cleaning variable pow */
    if((PyObject *)capi_fc_as_array!=fc_capi) {
        Py_XDECREF(capi_fc_as_array); }
    }  /* if (capi_fc_as_array == NULL) ... else of fc */
    /* End of cleaning variable fc */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of impose_asr_2nd ***************************/

/********************************* impose_asr *********************************/
static char doc_f2py_rout_secondorder_second_order_asr_impose_asr[] = "\
fc_out = impose_asr(fc,r2,pow,sclat,pbc,threshold,maxite,verbose,[nat,n_blocks])\n\nWrapper for ``impose_asr``.\
\n\nParameters\n----------\n"
"fc : input rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)\n"
"r2 : input rank-2 array('i') with bounds (3,n_blocks)\n"
"pow : input float\n"
"sclat : input rank-1 array('i') with bounds (3)\n"
"pbc : input int\n"
"threshold : input float\n"
"maxite : input int\n"
"verbose : input int\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(fc, 0) / 3\n"
"n_blocks : input int, optional\n    Default: shape(fc, 2)\n"
"\nReturns\n-------\n"
"fc_out : rank-3 array('d') with bounds (3 * nat,3 * nat,n_blocks)";
/*  */
static PyObject *f2py_rout_secondorder_second_order_asr_impose_asr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,int*,int*,double*,int*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *fc = NULL;
    npy_intp fc_Dims[3] = {-1, -1, -1};
    const int fc_Rank = 3;
    PyArrayObject *capi_fc_as_array = NULL;
    int capi_fc_intent = 0;
    PyObject *fc_capi = Py_None;
    int *r2 = NULL;
    npy_intp r2_Dims[2] = {-1, -1};
    const int r2_Rank = 2;
    PyArrayObject *capi_r2_as_array = NULL;
    int capi_r2_intent = 0;
    PyObject *r2_capi = Py_None;
    double pow = 0;
    PyObject *pow_capi = Py_None;
    int *sclat = NULL;
    npy_intp sclat_Dims[1] = {-1};
    const int sclat_Rank = 1;
    PyArrayObject *capi_sclat_as_array = NULL;
    int capi_sclat_intent = 0;
    PyObject *sclat_capi = Py_None;
    int pbc = 0;
    PyObject *pbc_capi = Py_None;
    double threshold = 0;
    PyObject *threshold_capi = Py_None;
    int maxite = 0;
    PyObject *maxite_capi = Py_None;
    double *fc_out = NULL;
    npy_intp fc_out_Dims[3] = {-1, -1, -1};
    const int fc_out_Rank = 3;
    PyArrayObject *capi_fc_out_as_array = NULL;
    int capi_fc_out_intent = 0;
    int verbose = 0;
    PyObject *verbose_capi = Py_None;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    int n_blocks = 0;
    PyObject *n_blocks_capi = Py_None;
    static char *capi_kwlist[] = {"fc","r2","pow","sclat","pbc","threshold","maxite","verbose","nat","n_blocks",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|OO:secondorder.second_order_asr.impose_asr",\
        capi_kwlist,&fc_capi,&r2_capi,&pow_capi,&sclat_capi,&pbc_capi,&threshold_capi,&maxite_capi,&verbose_capi,&nat_capi,&n_blocks_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable fc */
    ;
    capi_fc_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr: failed to create array from the 1st argument `fc`";
    capi_fc_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_Dims,fc_Rank,  capi_fc_intent,fc_capi,capi_errmess);
    if (capi_fc_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc = (double *)(PyArray_DATA(capi_fc_as_array));

    /* Processing variable pow */
        f2py_success = double_from_pyobj(&pow,pow_capi,"secondorder.second_order_asr.impose_asr() 3rd argument (pow) can't be converted to double");
    if (f2py_success) {
    /* Processing variable threshold */
        f2py_success = double_from_pyobj(&threshold,threshold_capi,"secondorder.second_order_asr.impose_asr() 6th argument (threshold) can't be converted to double");
    if (f2py_success) {
    /* Processing variable maxite */
        f2py_success = int_from_pyobj(&maxite,maxite_capi,"secondorder.second_order_asr.impose_asr() 7th argument (maxite) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sclat */
    sclat_Dims[0]=3;
    capi_sclat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr: failed to create array from the 4th argument `sclat`";
    capi_sclat_as_array = ndarray_from_pyobj(  NPY_INT,1,sclat_Dims,sclat_Rank,  capi_sclat_intent,sclat_capi,capi_errmess);
    if (capi_sclat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        sclat = (int *)(PyArray_DATA(capi_sclat_as_array));

    /* Processing variable pbc */
        pbc = (int)PyObject_IsTrue(pbc_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable verbose */
        verbose = (int)PyObject_IsTrue(verbose_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(fc, 0) / 3; else
        f2py_success = int_from_pyobj(&nat,nat_capi,"secondorder.second_order_asr.impose_asr() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 0) == 3 * nat,"shape(fc, 0) == 3 * nat","1st keyword nat","impose_asr:nat=%d",nat) {
    /* Processing variable n_blocks */
    if (n_blocks_capi == Py_None) n_blocks = shape(fc, 2); else
        f2py_success = int_from_pyobj(&n_blocks,n_blocks_capi,"secondorder.second_order_asr.impose_asr() 2nd keyword (n_blocks) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(fc, 2) == n_blocks,"shape(fc, 2) == n_blocks","2nd keyword n_blocks","impose_asr:n_blocks=%d",n_blocks) {
    /* Processing variable r2 */
    r2_Dims[0]=3,r2_Dims[1]=n_blocks;
    capi_r2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr: failed to create array from the 2nd argument `r2`";
    capi_r2_as_array = ndarray_from_pyobj(  NPY_INT,1,r2_Dims,r2_Rank,  capi_r2_intent,r2_capi,capi_errmess);
    if (capi_r2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        r2 = (int *)(PyArray_DATA(capi_r2_as_array));

    /* Processing variable fc_out */
    fc_out_Dims[0]=3 * nat,fc_out_Dims[1]=3 * nat,fc_out_Dims[2]=n_blocks;
    capi_fc_out_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "secondorder.secondorder.second_order_asr.impose_asr: failed to create array from the hidden `fc_out`";
    capi_fc_out_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fc_out_Dims,fc_out_Rank,  capi_fc_out_intent,Py_None,capi_errmess);
    if (capi_fc_out_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = secondorder_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fc_out = (double *)(PyArray_DATA(capi_fc_out_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(fc,r2,&pow,sclat,&pbc,&threshold,&maxite,fc_out,&verbose,&nat,&n_blocks);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_fc_out_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_fc_out_as_array == NULL) ... else of fc_out */
    /* End of cleaning variable fc_out */
    if((PyObject *)capi_r2_as_array!=r2_capi) {
        Py_XDECREF(capi_r2_as_array); }
    }  /* if (capi_r2_as_array == NULL) ... else of r2 */
    /* End of cleaning variable r2 */
    } /*CHECKSCALAR(shape(fc, 2) == n_blocks)*/
    } /*if (f2py_success) of n_blocks*/
    /* End of cleaning variable n_blocks */
    } /*CHECKSCALAR(shape(fc, 0) == 3 * nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    } /*if (f2py_success) of verbose*/
    /* End of cleaning variable verbose */
    } /*if (f2py_success) of pbc*/
    /* End of cleaning variable pbc */
    if((PyObject *)capi_sclat_as_array!=sclat_capi) {
        Py_XDECREF(capi_sclat_as_array); }
    }  /* if (capi_sclat_as_array == NULL) ... else of sclat */
    /* End of cleaning variable sclat */
    } /*if (f2py_success) of maxite*/
    /* End of cleaning variable maxite */
    } /*if (f2py_success) of threshold*/
    /* End of cleaning variable threshold */
    } /*if (f2py_success) of pow*/
    /* End of cleaning variable pow */
    if((PyObject *)capi_fc_as_array!=fc_capi) {
        Py_XDECREF(capi_fc_as_array); }
    }  /* if (capi_fc_as_array == NULL) ... else of fc */
    /* End of cleaning variable fc */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of impose_asr *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_second_order_centering_def[] = {
  {"analysis",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_centering_analysis,doc_f2py_rout_secondorder_second_order_centering_analysis},
  {"center",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_centering_center,doc_f2py_rout_secondorder_second_order_centering_center},
  {"within_dmax",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_centering_within_dmax,doc_f2py_rout_secondorder_second_order_centering_within_dmax},
  {"compute_perimeter",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_centering_compute_perimeter,doc_f2py_rout_secondorder_second_order_centering_compute_perimeter},
  {"cryst_to_cart",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_centering_cryst_to_cart,doc_f2py_rout_secondorder_second_order_centering_cryst_to_cart},
  {NULL}
};

static void f2py_setup_second_order_centering(char *analysis,char *center,char *within_dmax,char *compute_perimeter,char *cryst_to_cart) {
  int i_f2py=0;
  f2py_second_order_centering_def[i_f2py++].data = analysis;
  f2py_second_order_centering_def[i_f2py++].data = center;
  f2py_second_order_centering_def[i_f2py++].data = within_dmax;
  f2py_second_order_centering_def[i_f2py++].data = compute_perimeter;
  f2py_second_order_centering_def[i_f2py++].data = cryst_to_cart;
}
extern void F_FUNC_US(f2pyinitsecond_order_centering,F2PYINITSECOND_ORDER_CENTERING)(void (*)(char *,char *,char *,char *,char *));
static void f2py_init_second_order_centering(void) {
  F_FUNC_US(f2pyinitsecond_order_centering,F2PYINITSECOND_ORDER_CENTERING)(f2py_setup_second_order_centering);
}


static FortranDataDef f2py_second_order_asr_def[] = {
  {"perm_initialized",0,{{-1}},NPY_INT, 1},
  {"p",1,{{-1}},NPY_INT, 1},
  {"initialize_perm",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_initialize_perm,doc_f2py_rout_secondorder_second_order_asr_initialize_perm},
  {"clear_all",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_clear_all,doc_f2py_rout_secondorder_second_order_asr_clear_all},
  {"geq",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_geq,doc_f2py_rout_secondorder_second_order_asr_geq},
  {"impose_perm_sym",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_impose_perm_sym,doc_f2py_rout_secondorder_second_order_asr_impose_perm_sym},
  {"impose_asr_2nd",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_impose_asr_2nd,doc_f2py_rout_secondorder_second_order_asr_impose_asr_2nd},
  {"impose_asr",-1,{{-1}},0,0,NULL,(void *)f2py_rout_secondorder_second_order_asr_impose_asr,doc_f2py_rout_secondorder_second_order_asr_impose_asr},
  {NULL}
};

static void f2py_setup_second_order_asr(char *perm_initialized,void (*p)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char *initialize_perm,char *clear_all,char *geq,char *impose_perm_sym,char *impose_asr_2nd,char *impose_asr) {
  int i_f2py=0;
  f2py_second_order_asr_def[i_f2py++].data = perm_initialized;
  f2py_second_order_asr_def[i_f2py++].func = p;
  f2py_second_order_asr_def[i_f2py++].data = initialize_perm;
  f2py_second_order_asr_def[i_f2py++].data = clear_all;
  f2py_second_order_asr_def[i_f2py++].data = geq;
  f2py_second_order_asr_def[i_f2py++].data = impose_perm_sym;
  f2py_second_order_asr_def[i_f2py++].data = impose_asr_2nd;
  f2py_second_order_asr_def[i_f2py++].data = impose_asr;
}
extern void F_FUNC_US(f2pyinitsecond_order_asr,F2PYINITSECOND_ORDER_ASR)(void (*)(char*,void (*)(int*,npy_intp*,void(*)(char*,npy_intp*),int*),char *,char *,char *,char *,char *,char *));
static void f2py_init_second_order_asr(void) {
  F_FUNC_US(f2pyinitsecond_order_asr,F2PYINITSECOND_ORDER_ASR)(f2py_setup_second_order_asr);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "secondorder",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_secondorder(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = secondorder_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module secondorder (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'secondorder' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"Fortran 90/95 modules:\n""  second_order_centering --- analysis(),center(),within_dmax(),compute_perimeter(),cryst_to_cart()""  second_order_asr --- perm_initialized,p,initialize_perm(),clear_all(),geq(),impose_perm_sym(),impose_asr_2nd(),impose_asr()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    secondorder_error = PyErr_NewException ("secondorder.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_secondorder_error", secondorder_error);
    Py_DECREF(secondorder_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }











/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "second_order_asr", PyFortranObject_New(f2py_second_order_asr_def,f2py_init_second_order_asr));
  PyDict_SetItemString(d, "second_order_centering", PyFortranObject_New(f2py_second_order_centering_def,f2py_init_second_order_centering));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"secondorder");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
