!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapget_latvec (tau_sc, tau, itau, latvec, nat, nat&
     &_sc, nr, f2py_itau_d0)
      integer nat
      integer nat_sc
      integer nr
      integer f2py_itau_d0
      double precision tau_sc(3,nat_sc)
      double precision tau(3,nat)
      integer itau(f2py_itau_d0)
      double precision latvec(nr,3)
      interface
      
            subroutine get_latvec(tau_sc,tau,itau,latvec,nat,nat_sc,nr) 
                double precision, dimension(3,nat_sc),intent(in) :: tau_&
     &sc
                double precision, dimension(3, nat),intent(in) :: tau
                integer, dimension(:),intent(in) :: itau
                double precision, dimension(nr,3),intent(out) :: latvec
                integer :: nat
                integer :: nat_sc
                integer :: nr
            end subroutine get_latvec
      end interface
      call get_latvec(tau_sc, tau, itau, latvec, nat, nat_sc, nr)
      end


      
      subroutine f2pyinitconstants(f2pysetupfunc)
      use constants, only : pi
      use constants, only : tpi
      use constants, only : fpi
      use constants, only : sqrtpi
      use constants, only : sqrtpm1
      use constants, only : sqrt2
      use constants, only : h_planck_si
      use constants, only : k_boltzmann_si
      use constants, only : electron_si
      use constants, only : electronvolt_si
      use constants, only : electronmass_si
      use constants, only : hartree_si
      use constants, only : rydberg_si
      use constants, only : bohr_radius_si
      use constants, only : amu_si
      use constants, only : c_si
      use constants, only : munought_si
      use constants, only : epsnought_si
      use constants, only : k_boltzmann_au
      use constants, only : k_boltzmann_ry
      use constants, only : autoev
      use constants, only : rytoev
      use constants, only : amu_au
      use constants, only : amu_ry
      use constants, only : au_sec
      use constants, only : au_ps
      use constants, only : au_gpa
      use constants, only : ry_kbar
      use constants, only : debye_si
      use constants, only : au_debye
      use constants, only : ev_to_kelvin
      use constants, only : ry_to_kelvin
      use constants, only : evtonm
      use constants, only : rytonm
      use constants, only : c_au
      use constants, only : eps4
      use constants, only : eps6
      use constants, only : eps8
      use constants, only : eps12
      use constants, only : eps14
      use constants, only : eps16
      use constants, only : eps24
      use constants, only : eps32
      use constants, only : gsmall
      use constants, only : e2
      use constants, only : degspin
      use constants, only : bohr_radius_cm
      use constants, only : bohr_radius_angs
      use constants, only : angstrom_au
      use constants, only : dip_debye
      use constants, only : au_terahertz
      use constants, only : au_to_ohmcmm1
      use constants, only : ry_to_thz
      use constants, only : ry_to_ghz
      use constants, only : ry_to_cmm1
      use constants, only : avogadro
      external f2pysetupfunc
      call f2pysetupfunc(pi,tpi,fpi,sqrtpi,sqrtpm1,sqrt2,h_planck_si,k_b&
     &oltzmann_si,electron_si,electronvolt_si,electronmass_si,hartree_si&
     &,rydberg_si,bohr_radius_si,amu_si,c_si,munought_si,epsnought_si,k_&
     &boltzmann_au,k_boltzmann_ry,autoev,rytoev,amu_au,amu_ry,au_sec,au_&
     &ps,au_gpa,ry_kbar,debye_si,au_debye,ev_to_kelvin,ry_to_kelvin,evto&
     &nm,rytonm,c_au,eps4,eps6,eps8,eps12,eps14,eps16,eps24,eps32,gsmall&
     &,e2,degspin,bohr_radius_cm,bohr_radius_angs,angstrom_au,dip_debye,&
     &au_terahertz,au_to_ohmcmm1,ry_to_thz,ry_to_ghz,ry_to_cmm1,avogadro&
     &)
      end subroutine f2pyinitconstants

      
      subroutine f2pyinitio_global(f2pysetupfunc)
      use io_global, only : stdout
      use io_global, only : ionode
      use io_global, only : ionode_id
      use io_global, only : meta_ionode
      use io_global, only : meta_ionode_id
      use io_global, only : xmlinputunit
      use io_global, only : xmloutputunit
      use io_global, only : xmltmpunit
      use io_global, only : io_global_start
      use io_global, only : meta_io_global_start
      use io_global, only : io_global_getionode
      use io_global, only : io_global_getmeta
      external f2pysetupfunc
      call f2pysetupfunc(stdout,ionode,ionode_id,meta_ionode,meta_ionode&
     &_id,xmlinputunit,xmloutputunit,xmltmpunit,io_global_start,meta_io_&
     &global_start,io_global_getionode,io_global_getmeta)
      end subroutine f2pyinitio_global

      
      subroutine f2pyinitkinds(f2pysetupfunc)
      use kinds, only : dp
      use kinds, only : sgl
      use kinds, only : i4b
      use kinds, only : print_kind_info
      external f2pysetupfunc
      call f2pysetupfunc(dp,sgl,i4b,print_kind_info)
      end subroutine f2pyinitkinds

      subroutine f2py_symm_base_getdims_irt(r,s,f2pysetdata,flag)
      use symm_base, only: d => irt

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_symm_base_getdims_irt
      subroutine f2pywrap_symm_base_copy_sym (copy_symf2pywrap, nrot_, s&
     &ym)
      use symm_base, only : copy_sym
      integer nrot_
      logical sym(48)
      integer copy_symf2pywrap
      copy_symf2pywrap = copy_sym(nrot_, sym)
      end subroutine f2pywrap_symm_base_copy_sym
      subroutine f2pywrap_symm_base_is_group (is_groupf2pywrap)
      use symm_base, only : is_group
      logical is_groupf2pywrap
      is_groupf2pywrap = .not.(.not.is_group())
      end subroutine f2pywrap_symm_base_is_group
      subroutine f2pywrap_symm_base_eqvect (eqvectf2pywrap, x, y, f)
      use symm_base, only : eqvect
      double precision x(3)
      double precision y(3)
      double precision f(3)
      logical eqvectf2pywrap
      eqvectf2pywrap = .not.(.not.eqvect(x, y, f))
      end subroutine f2pywrap_symm_base_eqvect
      subroutine f2pywrap_symm_base_checksym (checksymf2pywrap, irot, na&
     &t, ityp, xau, rau, ft_)
      use symm_base, only : checksym
      integer irot
      integer nat
      integer ityp(nat)
      double precision xau(3,nat)
      double precision rau(3,nat)
      double precision ft_(3)
      logical checksymf2pywrap
      checksymf2pywrap = .not.(.not.checksym(irot, nat, ityp, xau, rau, &
     &ft_))
      end subroutine f2pywrap_symm_base_checksym
      
      subroutine f2pyinitsymm_base(f2pysetupfunc)
      use symm_base, only : eps1
      use symm_base, only : eps2
      use symm_base, only : s
      use symm_base, only : sr
      use symm_base, only : sname
      use symm_base, only : ft
      use symm_base, only : ftau
      use symm_base, only : nrot
      use symm_base, only : nsym
      use symm_base, only : nsym_ns
      use symm_base, only : nsym_na
      use symm_base, only : t_rev
      use symm_base, only : no_t_rev
      use symm_base, only : time_reversal
      use symm_base, only : irt
      use symm_base, only : invs
      use symm_base, only : invsym
      use symm_base, only : d1
      use symm_base, only : d2
      use symm_base, only : d3
      use symm_base, only : allfrac
      use symm_base, only : nofrac
      use symm_base, only : nosym
      use symm_base, only : nosym_evc
      use symm_base, only : at
      use symm_base, only : bg
      use symm_base, only : set_accep_threshold
      use symm_base, only : get_accep_threshold
      use symm_base, only : set_at_bg
      use symm_base, only : inverse_s
      use symm_base, only : set_sym_bl
      use symm_base, only : find_sym
      use symm_base, only : sgam_at
      use symm_base, only : sgam_at_mag
      use symm_base, only : set_sym
      use symm_base, only : checkallsym
      use symm_base, only : s_axis_to_cart
      use symm_base, only : smallg_q
      interface 
      subroutine f2pywrap_symm_base_copy_sym (copy_symf2pywrap, nrot_, s&
     &ym)
      integer nrot_
      logical sym(48)
      integer copy_symf2pywrap
      end subroutine f2pywrap_symm_base_copy_sym 
      subroutine f2pywrap_symm_base_is_group (is_groupf2pywrap, is_group&
     &)
      logical is_groupf2pywrap
      end subroutine f2pywrap_symm_base_is_group 
      subroutine f2pywrap_symm_base_eqvect (eqvectf2pywrap, x, y, f)
      double precision x(3)
      double precision y(3)
      double precision f(3)
      logical eqvectf2pywrap
      end subroutine f2pywrap_symm_base_eqvect 
      subroutine f2pywrap_symm_base_checksym (checksymf2pywrap, irot, na&
     &t, ityp, xau, rau, ft_)
      integer irot
      integer nat
      integer ityp(nat)
      double precision xau(3,nat)
      double precision rau(3,nat)
      double precision ft_(3)
      logical checksymf2pywrap
      end subroutine f2pywrap_symm_base_checksym
      end interface
      external f2pysetupfunc
      external f2py_symm_base_getdims_irt
      call f2pysetupfunc(eps1,eps2,s,sr,sname,ft,ftau,nrot,nsym,nsym_ns,&
     &nsym_na,t_rev,no_t_rev,time_reversal,f2py_symm_base_getdims_irt,in&
     &vs,invsym,d1,d2,d3,allfrac,nofrac,nosym,nosym_evc,at,bg,set_accep_&
     &threshold,get_accep_threshold,set_at_bg,inverse_s,set_sym_bl,find_&
     &sym,sgam_at,sgam_at_mag,set_sym,f2pywrap_symm_base_copy_sym,f2pywr&
     &ap_symm_base_is_group,f2pywrap_symm_base_eqvect,f2pywrap_symm_base&
     &_checksym,checkallsym,s_axis_to_cart,smallg_q)
      end subroutine f2pyinitsymm_base


