C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapwsweight (wsweightf2pywrap, r, rws, nrws,
     & nrwsx)
      external wsweight
      integer nrws
      integer nrwsx
      double precision r(3)
      double precision rws(4,nrwsx)
      double precision wsweightf2pywrap
      double precision  wsweight
      wsweightf2pywrap = wsweight(r, rws, nrws, nrwsx)
      end


      subroutine f2pywrapeqvect (eqvectf2pywrap, x, y, f)
      external eqvect
      double precision x(3)
      double precision y(3)
      double precision f(3)
      logical eqvectf2pywrap
      logical  eqvect
      eqvectf2pywrap = .not.(.not.eqvect(x, y, f))
      end

