!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_get_lf_vec_dot_mat (vec_dot_matf2pywrap, v1, m&
     &1, f2py_v1_d0, f2py_m1_d0, f2py_m1_d1)
      use get_lf, only : vec_dot_mat
      integer f2py_v1_d0
      integer f2py_m1_d0
      integer f2py_m1_d1
      real(kind=8) v1(f2py_v1_d0)
      real(kind=8) m1(f2py_m1_d0,f2py_m1_d1)
      real(kind=8) vec_dot_matf2pywrap(size(v1))
      vec_dot_matf2pywrap = vec_dot_mat(v1, m1)
      end subroutine f2pywrap_get_lf_vec_dot_mat
      subroutine f2pywrap_get_lf_inv (invf2pywrap, a, f2py_a_d0, f2py_a_&
     &d1)
      use get_lf, only : inv
      integer f2py_a_d0
      integer f2py_a_d1
      real(kind=8) a(f2py_a_d0,f2py_a_d1)
      real(kind=8) invf2pywrap(size(a, 1),size(a, 2))
      invf2pywrap = inv(a)
      end subroutine f2pywrap_get_lf_inv
      
      subroutine f2pyinitget_lf(f2pysetupfunc)
      use get_lf, only : calculate_lineshapes
      use get_lf, only : calculate_lineshapes_mode_mixing
      use get_lf, only : calculate_lineshapes_cartesian
      use get_lf, only : calculate_lifetimes_selfconsistently
      use get_lf, only : solve_selfconsistent_equation
      use get_lf, only : calculate_correlation_function
      use get_lf, only : calculate_lifetimes_perturbative
      use get_lf, only : calculate_lifetimes
      use get_lf, only : calculate_self_energy_la
      use get_lf, only : calculate_self_energy_p
      use get_lf, only : calculate_self_energy_full
      use get_lf, only : check_if_gamma
      use get_lf, only : calculate_real_part_via_kramers_kronig
      use get_lf, only : calculate_real_part_via_kramers_kronig_2d
      use get_lf, only : hilbert_transform_via_fft
      use get_lf, only : ht
      use get_lf, only : cfft
      use get_lf, only : interpolate_fc2
      interface 
      subroutine f2pywrap_get_lf_vec_dot_mat (vec_dot_matf2pywrap, v1, m&
     &1, f2py_v1_d0, f2py_m1_d0, f2py_m1_d1)
      integer f2py_v1_d0
      integer f2py_m1_d0
      integer f2py_m1_d1
      real(kind=8) v1(f2py_v1_d0)
      real(kind=8) m1(f2py_m1_d0,f2py_m1_d1)
      real(kind=8) vec_dot_matf2pywrap(size(v1))
      end subroutine f2pywrap_get_lf_vec_dot_mat 
      subroutine f2pywrap_get_lf_inv (invf2pywrap, a, f2py_a_d0, f2py_a_&
     &d1)
      integer f2py_a_d0
      integer f2py_a_d1
      real(kind=8) a(f2py_a_d0,f2py_a_d1)
      real(kind=8) invf2pywrap(size(a, 1),size(a, 2))
      end subroutine f2pywrap_get_lf_inv
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(calculate_lineshapes,calculate_lineshapes_mode_&
     &mixing,calculate_lineshapes_cartesian,calculate_lifetimes_selfcons&
     &istently,solve_selfconsistent_equation,calculate_correlation_funct&
     &ion,calculate_lifetimes_perturbative,calculate_lifetimes,calculate&
     &_self_energy_la,calculate_self_energy_p,calculate_self_energy_full&
     &,check_if_gamma,f2pywrap_get_lf_vec_dot_mat,calculate_real_part_vi&
     &a_kramers_kronig,calculate_real_part_via_kramers_kronig_2d,hilbert&
     &_transform_via_fft,ht,cfft,f2pywrap_get_lf_inv,interpolate_fc2)
      end subroutine f2pyinitget_lf

      subroutine f2pywrap_scattering_grids_same_vector (same_vectorf2pyw&
     &rap, v1, v2)
      use scattering_grids, only : same_vector
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical same_vectorf2pywrap
      same_vectorf2pywrap = .not.(.not.same_vector(v1, v2))
      end subroutine f2pywrap_scattering_grids_same_vector
      subroutine f2pywrap_scattering_grids_same_vector_nopbc (same_vecto&
     &r_nopbcf2pywrap, v1, v2)
      use scattering_grids, only : same_vector_nopbc
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical same_vector_nopbcf2pywrap
      same_vector_nopbcf2pywrap = .not.(.not.same_vector_nopbc(v1, v2))
      end subroutine f2pywrap_scattering_grids_same_vector_nopbc
      
      subroutine f2pyinitscattering_grids(f2pysetupfunc)
      use scattering_grids, only : get_scattering_q_grid
      interface 
      subroutine f2pywrap_scattering_grids_same_vector (same_vectorf2pyw&
     &rap, v1, v2)
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical same_vectorf2pywrap
      end subroutine f2pywrap_scattering_grids_same_vector 
      subroutine f2pywrap_scattering_grids_same_vector_nopbc (same_vecto&
     &r_nopbcf2pywrap, v1, v2)
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      logical same_vector_nopbcf2pywrap
      end subroutine f2pywrap_scattering_grids_same_vector_nopbc
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(get_scattering_q_grid,f2pywrap_scattering_grids&
     &_same_vector,f2pywrap_scattering_grids_same_vector_nopbc)
      end subroutine f2pyinitscattering_grids

      subroutine f2pywrap_third_order_centering_within_dmax (within_dmax&
     &f2pywrap, v1, v2, v3, d1, d2, d3, tol)
      use third_order_centering, only : within_dmax
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) d3
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      logical within_dmaxf2pywrap
      within_dmaxf2pywrap = .not.(.not.within_dmax(v1, v2, v3, d1, d2, d&
     &3, tol))
      end subroutine f2pywrap_third_order_centering_within_dmax
      subroutine f2pywrap_third_order_centering_compute_perimeter (compu&
     &te_perimeterf2pywrap, v1, v2, v3)
      use third_order_centering, only : compute_perimeter
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      real(kind=8) compute_perimeterf2pywrap
      compute_perimeterf2pywrap = compute_perimeter(v1, v2, v3)
      end subroutine f2pywrap_third_order_centering_compute_perimeter
      subroutine f2pywrap_third_order_centering_three_to_one_len (three_&
     &to_one_lenf2pywrap, v, v_min, v_len)
      use third_order_centering, only : three_to_one_len
      integer v(3)
      integer v_min(3)
      integer v_len(3)
      integer three_to_one_lenf2pywrap
      three_to_one_lenf2pywrap = three_to_one_len(v, v_min, v_len)
      end subroutine f2pywrap_third_order_centering_three_to_one_len
      subroutine f2pywrap_third_order_centering_three_to_one (three_to_o&
     &nef2pywrap, v, v_min, v_max)
      use third_order_centering, only : three_to_one
      integer v(3)
      integer v_min(3)
      integer v_max(3)
      integer three_to_onef2pywrap
      three_to_onef2pywrap = three_to_one(v, v_min, v_max)
      end subroutine f2pywrap_third_order_centering_three_to_one
      subroutine f2pywrap_third_order_centering_one_to_three_len (one_to&
     &_three_lenf2pywrap, j, v_min, v_len)
      use third_order_centering, only : one_to_three_len
      integer j
      integer v_min(3)
      integer v_len(3)
      integer one_to_three_lenf2pywrap(3)
      one_to_three_lenf2pywrap = one_to_three_len(j, v_min, v_len)
      end subroutine f2pywrap_third_order_centering_one_to_three_len
      subroutine f2pywrap_third_order_centering_one_to_three (one_to_thr&
     &eef2pywrap, j, v_min, v_max)
      use third_order_centering, only : one_to_three
      integer j
      integer v_min(3)
      integer v_max(3)
      integer one_to_threef2pywrap(3)
      one_to_threef2pywrap = one_to_three(j, v_min, v_max)
      end subroutine f2pywrap_third_order_centering_one_to_three
      subroutine f2pywrap_third_order_centering_min_el_wise_2 (min_el_wi&
     &se_2f2pywrap, a, b)
      use third_order_centering, only : min_el_wise_2
      integer a(3)
      integer b(3)
      integer min_el_wise_2f2pywrap(3)
      min_el_wise_2f2pywrap = min_el_wise_2(a, b)
      end subroutine f2pywrap_third_order_centering_min_el_wise_2
      subroutine f2pywrap_third_order_centering_max_el_wise_2 (max_el_wi&
     &se_2f2pywrap, a, b)
      use third_order_centering, only : max_el_wise_2
      integer a(3)
      integer b(3)
      integer max_el_wise_2f2pywrap(3)
      max_el_wise_2f2pywrap = max_el_wise_2(a, b)
      end subroutine f2pywrap_third_order_centering_max_el_wise_2
      subroutine f2pywrap_third_order_centering_min_el_wise_3 (min_el_wi&
     &se_3f2pywrap, a, b, c)
      use third_order_centering, only : min_el_wise_3
      integer a(3)
      integer b(3)
      integer c(3)
      integer min_el_wise_3f2pywrap(3)
      min_el_wise_3f2pywrap = min_el_wise_3(a, b, c)
      end subroutine f2pywrap_third_order_centering_min_el_wise_3
      subroutine f2pywrap_third_order_centering_max_el_wise_3 (max_el_wi&
     &se_3f2pywrap, a, b, c)
      use third_order_centering, only : max_el_wise_3
      integer a(3)
      integer b(3)
      integer c(3)
      integer max_el_wise_3f2pywrap(3)
      max_el_wise_3f2pywrap = max_el_wise_3(a, b, c)
      end subroutine f2pywrap_third_order_centering_max_el_wise_3
      subroutine f2pywrap_third_order_centering_cryst_to_cart (cryst_to_&
     &cartf2pywrap, v, alat)
      use third_order_centering, only : cryst_to_cart
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      cryst_to_cartf2pywrap = cryst_to_cart(v, alat)
      end subroutine f2pywrap_third_order_centering_cryst_to_cart
      
      subroutine f2pyinitthird_order_centering(f2pysetupfunc)
      use third_order_centering, only : analysis
      use third_order_centering, only : center
      use third_order_centering, only : center_sparse
      use third_order_centering, only : pre_center
      use third_order_centering, only : assign
      interface 
      subroutine f2pywrap_third_order_centering_within_dmax (within_dmax&
     &f2pywrap, v1, v2, v3, d1, d2, d3, tol)
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) d3
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      logical within_dmaxf2pywrap
      end subroutine f2pywrap_third_order_centering_within_dmax 
      subroutine f2pywrap_third_order_centering_compute_perimeter (compu&
     &te_perimeterf2pywrap, v1, v2, v3)
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      real(kind=8) compute_perimeterf2pywrap
      end subroutine f2pywrap_third_order_centering_compute_perimeter 
      subroutine f2pywrap_third_order_centering_three_to_one_len (three_&
     &to_one_lenf2pywrap, v, v_min, v_len)
      integer v(3)
      integer v_min(3)
      integer v_len(3)
      integer three_to_one_lenf2pywrap
      end subroutine f2pywrap_third_order_centering_three_to_one_len 
      subroutine f2pywrap_third_order_centering_three_to_one (three_to_o&
     &nef2pywrap, v, v_min, v_max)
      integer v(3)
      integer v_min(3)
      integer v_max(3)
      integer three_to_onef2pywrap
      end subroutine f2pywrap_third_order_centering_three_to_one 
      subroutine f2pywrap_third_order_centering_one_to_three_len (one_to&
     &_three_lenf2pywrap, j, v_min, v_len)
      integer j
      integer v_min(3)
      integer v_len(3)
      integer one_to_three_lenf2pywrap(3)
      end subroutine f2pywrap_third_order_centering_one_to_three_len 
      subroutine f2pywrap_third_order_centering_one_to_three (one_to_thr&
     &eef2pywrap, j, v_min, v_max)
      integer j
      integer v_min(3)
      integer v_max(3)
      integer one_to_threef2pywrap(3)
      end subroutine f2pywrap_third_order_centering_one_to_three 
      subroutine f2pywrap_third_order_centering_min_el_wise_2 (min_el_wi&
     &se_2f2pywrap, a, b)
      integer a(3)
      integer b(3)
      integer min_el_wise_2f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_min_el_wise_2 
      subroutine f2pywrap_third_order_centering_max_el_wise_2 (max_el_wi&
     &se_2f2pywrap, a, b)
      integer a(3)
      integer b(3)
      integer max_el_wise_2f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_max_el_wise_2 
      subroutine f2pywrap_third_order_centering_min_el_wise_3 (min_el_wi&
     &se_3f2pywrap, a, b, c)
      integer a(3)
      integer b(3)
      integer c(3)
      integer min_el_wise_3f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_min_el_wise_3 
      subroutine f2pywrap_third_order_centering_max_el_wise_3 (max_el_wi&
     &se_3f2pywrap, a, b, c)
      integer a(3)
      integer b(3)
      integer c(3)
      integer max_el_wise_3f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_max_el_wise_3 
      subroutine f2pywrap_third_order_centering_cryst_to_cart (cryst_to_&
     &cartf2pywrap, v, alat)
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      end subroutine f2pywrap_third_order_centering_cryst_to_cart
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(analysis,center,center_sparse,pre_center,assign&
     &,f2pywrap_third_order_centering_within_dmax,f2pywrap_third_order_c&
     &entering_compute_perimeter,f2pywrap_third_order_centering_three_to&
     &_one_len,f2pywrap_third_order_centering_three_to_one,f2pywrap_thir&
     &d_order_centering_one_to_three_len,f2pywrap_third_order_centering_&
     &one_to_three,f2pywrap_third_order_centering_min_el_wise_2,f2pywrap&
     &_third_order_centering_max_el_wise_2,f2pywrap_third_order_centerin&
     &g_min_el_wise_3,f2pywrap_third_order_centering_max_el_wise_3,f2pyw&
     &rap_third_order_centering_cryst_to_cart)
      end subroutine f2pyinitthird_order_centering

      subroutine f2pywrap_third_order_cond_f_bose (f_bosef2pywrap, freq,&
     & t)
      use third_order_cond, only : f_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      f_bosef2pywrap = f_bose(freq, t)
      end subroutine f2pywrap_third_order_cond_f_bose
      subroutine f2pywrap_third_order_cond_df_bose (df_bosef2pywrap, fre&
     &q, t)
      use third_order_cond, only : df_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      df_bosef2pywrap = df_bose(freq, t)
      end subroutine f2pywrap_third_order_cond_df_bose
      subroutine f2pywrap_third_order_cond_gaussian_function (gaussian_f&
     &unctionf2pywrap, x, sigma)
      use third_order_cond, only : gaussian_function
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) gaussian_functionf2pywrap
      gaussian_functionf2pywrap = gaussian_function(x, sigma)
      end subroutine f2pywrap_third_order_cond_gaussian_function
      subroutine f2pywrap_third_order_cond_cinv (cinvf2pywrap, a, f2py_a&
     &_d0, f2py_a_d1)
      use third_order_cond, only : cinv
      integer f2py_a_d0
      integer f2py_a_d1
      complex(kind=8) a(f2py_a_d0,f2py_a_d1)
      complex(kind=8) cinvf2pywrap(size(a, 1),size(a, 2))
      cinvf2pywrap = cinv(a)
      end subroutine f2pywrap_third_order_cond_cinv
      
      subroutine f2pyinitthird_order_cond(f2pysetupfunc)
      use third_order_cond, only : interpol_v2
      use third_order_cond, only : interpol_v3
      use third_order_cond, only : compute_full_dynamic_bubble_single
      use third_order_cond, only : compute_diag_dynamic_bubble_single
      use third_order_cond, only : compute_perturb_selfnrg_single
      use third_order_cond, only : compute_spectralf_diag_single
      use third_order_cond, only : lambda_dynamic_single
      use third_order_cond, only : lambda_dynamic_value_single
      use third_order_cond, only : calculate_spectral_function
      use third_order_cond, only : calculate_spectral_function_mode_mixi&
     &ng
      use third_order_cond, only : calculate_spectral_function_cartesian
      use third_order_cond, only : bose_freq
      use third_order_cond, only : eq_freq
      use third_order_cond, only : eliminate_transl
      interface 
      subroutine f2pywrap_third_order_cond_f_bose (f_bosef2pywrap, freq,&
     & t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      end subroutine f2pywrap_third_order_cond_f_bose 
      subroutine f2pywrap_third_order_cond_df_bose (df_bosef2pywrap, fre&
     &q, t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      end subroutine f2pywrap_third_order_cond_df_bose 
      subroutine f2pywrap_third_order_cond_gaussian_function (gaussian_f&
     &unctionf2pywrap, x, sigma)
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) gaussian_functionf2pywrap
      end subroutine f2pywrap_third_order_cond_gaussian_function 
      subroutine f2pywrap_third_order_cond_cinv (cinvf2pywrap, a, f2py_a&
     &_d0, f2py_a_d1)
      integer f2py_a_d0
      integer f2py_a_d1
      complex(kind=8) a(f2py_a_d0,f2py_a_d1)
      complex(kind=8) cinvf2pywrap(size(a, 1),size(a, 2))
      end subroutine f2pywrap_third_order_cond_cinv
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(interpol_v2,interpol_v3,compute_full_dynamic_bu&
     &bble_single,compute_diag_dynamic_bubble_single,compute_perturb_sel&
     &fnrg_single,compute_spectralf_diag_single,lambda_dynamic_single,la&
     &mbda_dynamic_value_single,calculate_spectral_function,calculate_sp&
     &ectral_function_mode_mixing,calculate_spectral_function_cartesian,&
     &bose_freq,eq_freq,f2pywrap_third_order_cond_f_bose,f2pywrap_third_&
     &order_cond_df_bose,f2pywrap_third_order_cond_gaussian_function,eli&
     &minate_transl,f2pywrap_third_order_cond_cinv)
      end subroutine f2pyinitthird_order_cond


