!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_third_order_asr_getdims_p(r,s,f2pysetdata,flag)
      use third_order_asr, only: d => p

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_third_order_asr_getdims_p
      subroutine f2py_third_order_asr_getdims_index_blocks_r2(r,s,f2pyse&
     &tdata,flag)
      use third_order_asr, only: d => index_blocks_r2

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_third_order_asr_getdims_index_blocks_r2
      subroutine f2py_third_order_asr_getdims_num_blocks_r2(r,s,f2pysetd&
     &ata,flag)
      use third_order_asr, only: d => num_blocks_r2

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_third_order_asr_getdims_num_blocks_r2
      subroutine f2pywrap_third_order_asr_geq (geqf2pywrap, v1, v2, lat,&
     & pbc, f2py_v1_d0, f2py_v2_d0, f2py_lat_d0)
      use third_order_asr, only : geq
      logical pbc
      integer f2py_v1_d0
      integer f2py_v2_d0
      integer f2py_lat_d0
      integer v1(f2py_v1_d0)
      integer v2(f2py_v2_d0)
      integer lat(f2py_lat_d0)
      logical geqf2pywrap
      geqf2pywrap = .not.(.not.geq(v1, v2, lat, pbc))
      end subroutine f2pywrap_third_order_asr_geq
      subroutine f2pywrap_third_order_asr_f (ff2pywrap, x)
      use third_order_asr, only : f
      integer x(6)
      integer ff2pywrap(6,5)
      ff2pywrap = f(x)
      end subroutine f2pywrap_third_order_asr_f
      
      subroutine f2pyinitthird_order_asr(f2pysetupfunc)
      use third_order_asr, only : perm_initialized
      use third_order_asr, only : p
      use third_order_asr, only : r2index_initialized
      use third_order_asr, only : index_blocks_r2
      use third_order_asr, only : num_blocks_r2
      use third_order_asr, only : initialize_r2index
      use third_order_asr, only : initialize_perm
      use third_order_asr, only : impose_perm_sym
      use third_order_asr, only : impose_asr_3rd
      use third_order_asr, only : impose_asr
      interface 
      subroutine f2pywrap_third_order_asr_geq (geqf2pywrap, v1, v2, lat,&
     & pbc, f2py_v1_d0, f2py_v2_d0, f2py_lat_d0)
      logical pbc
      integer f2py_v1_d0
      integer f2py_v2_d0
      integer f2py_lat_d0
      integer v1(f2py_v1_d0)
      integer v2(f2py_v2_d0)
      integer lat(f2py_lat_d0)
      logical geqf2pywrap
      end subroutine f2pywrap_third_order_asr_geq 
      subroutine f2pywrap_third_order_asr_f (ff2pywrap, x)
      integer x(6)
      integer ff2pywrap(6,5)
      end subroutine f2pywrap_third_order_asr_f
      end interface
      external f2pysetupfunc
      external f2py_third_order_asr_getdims_p
      external f2py_third_order_asr_getdims_index_blocks_r2
      external f2py_third_order_asr_getdims_num_blocks_r2
      call f2pysetupfunc(perm_initialized,f2py_third_order_asr_getdims_p&
     &,r2index_initialized,f2py_third_order_asr_getdims_index_blocks_r2,&
     &f2py_third_order_asr_getdims_num_blocks_r2,initialize_r2index,init&
     &ialize_perm,f2pywrap_third_order_asr_geq,f2pywrap_third_order_asr_&
     &f,impose_perm_sym,impose_asr_3rd,impose_asr)
      end subroutine f2pyinitthird_order_asr

      subroutine f2pywrap_third_order_centering_within_dmax (within_dmax&
     &f2pywrap, v1, v2, v3, d1, d2, d3, tol)
      use third_order_centering, only : within_dmax
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) d3
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      logical within_dmaxf2pywrap
      within_dmaxf2pywrap = .not.(.not.within_dmax(v1, v2, v3, d1, d2, d&
     &3, tol))
      end subroutine f2pywrap_third_order_centering_within_dmax
      subroutine f2pywrap_third_order_centering_compute_perimeter (compu&
     &te_perimeterf2pywrap, v1, v2, v3)
      use third_order_centering, only : compute_perimeter
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      real(kind=8) compute_perimeterf2pywrap
      compute_perimeterf2pywrap = compute_perimeter(v1, v2, v3)
      end subroutine f2pywrap_third_order_centering_compute_perimeter
      subroutine f2pywrap_third_order_centering_three_to_one_len (three_&
     &to_one_lenf2pywrap, v, v_min, v_len)
      use third_order_centering, only : three_to_one_len
      integer v(3)
      integer v_min(3)
      integer v_len(3)
      integer three_to_one_lenf2pywrap
      three_to_one_lenf2pywrap = three_to_one_len(v, v_min, v_len)
      end subroutine f2pywrap_third_order_centering_three_to_one_len
      subroutine f2pywrap_third_order_centering_three_to_one (three_to_o&
     &nef2pywrap, v, v_min, v_max)
      use third_order_centering, only : three_to_one
      integer v(3)
      integer v_min(3)
      integer v_max(3)
      integer three_to_onef2pywrap
      three_to_onef2pywrap = three_to_one(v, v_min, v_max)
      end subroutine f2pywrap_third_order_centering_three_to_one
      subroutine f2pywrap_third_order_centering_one_to_three_len (one_to&
     &_three_lenf2pywrap, j, v_min, v_len)
      use third_order_centering, only : one_to_three_len
      integer j
      integer v_min(3)
      integer v_len(3)
      integer one_to_three_lenf2pywrap(3)
      one_to_three_lenf2pywrap = one_to_three_len(j, v_min, v_len)
      end subroutine f2pywrap_third_order_centering_one_to_three_len
      subroutine f2pywrap_third_order_centering_one_to_three (one_to_thr&
     &eef2pywrap, j, v_min, v_max)
      use third_order_centering, only : one_to_three
      integer j
      integer v_min(3)
      integer v_max(3)
      integer one_to_threef2pywrap(3)
      one_to_threef2pywrap = one_to_three(j, v_min, v_max)
      end subroutine f2pywrap_third_order_centering_one_to_three
      subroutine f2pywrap_third_order_centering_min_el_wise_2 (min_el_wi&
     &se_2f2pywrap, a, b)
      use third_order_centering, only : min_el_wise_2
      integer a(3)
      integer b(3)
      integer min_el_wise_2f2pywrap(3)
      min_el_wise_2f2pywrap = min_el_wise_2(a, b)
      end subroutine f2pywrap_third_order_centering_min_el_wise_2
      subroutine f2pywrap_third_order_centering_max_el_wise_2 (max_el_wi&
     &se_2f2pywrap, a, b)
      use third_order_centering, only : max_el_wise_2
      integer a(3)
      integer b(3)
      integer max_el_wise_2f2pywrap(3)
      max_el_wise_2f2pywrap = max_el_wise_2(a, b)
      end subroutine f2pywrap_third_order_centering_max_el_wise_2
      subroutine f2pywrap_third_order_centering_min_el_wise_3 (min_el_wi&
     &se_3f2pywrap, a, b, c)
      use third_order_centering, only : min_el_wise_3
      integer a(3)
      integer b(3)
      integer c(3)
      integer min_el_wise_3f2pywrap(3)
      min_el_wise_3f2pywrap = min_el_wise_3(a, b, c)
      end subroutine f2pywrap_third_order_centering_min_el_wise_3
      subroutine f2pywrap_third_order_centering_max_el_wise_3 (max_el_wi&
     &se_3f2pywrap, a, b, c)
      use third_order_centering, only : max_el_wise_3
      integer a(3)
      integer b(3)
      integer c(3)
      integer max_el_wise_3f2pywrap(3)
      max_el_wise_3f2pywrap = max_el_wise_3(a, b, c)
      end subroutine f2pywrap_third_order_centering_max_el_wise_3
      subroutine f2pywrap_third_order_centering_cryst_to_cart (cryst_to_&
     &cartf2pywrap, v, alat)
      use third_order_centering, only : cryst_to_cart
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      cryst_to_cartf2pywrap = cryst_to_cart(v, alat)
      end subroutine f2pywrap_third_order_centering_cryst_to_cart
      
      subroutine f2pyinitthird_order_centering(f2pysetupfunc)
      use third_order_centering, only : analysis
      use third_order_centering, only : center
      use third_order_centering, only : center_sparse
      use third_order_centering, only : pre_center
      use third_order_centering, only : assign
      interface 
      subroutine f2pywrap_third_order_centering_within_dmax (within_dmax&
     &f2pywrap, v1, v2, v3, d1, d2, d3, tol)
      real(kind=8) d1
      real(kind=8) d2
      real(kind=8) d3
      real(kind=8) tol
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      logical within_dmaxf2pywrap
      end subroutine f2pywrap_third_order_centering_within_dmax 
      subroutine f2pywrap_third_order_centering_compute_perimeter (compu&
     &te_perimeterf2pywrap, v1, v2, v3)
      real(kind=8) v1(3)
      real(kind=8) v2(3)
      real(kind=8) v3(3)
      real(kind=8) compute_perimeterf2pywrap
      end subroutine f2pywrap_third_order_centering_compute_perimeter 
      subroutine f2pywrap_third_order_centering_three_to_one_len (three_&
     &to_one_lenf2pywrap, v, v_min, v_len)
      integer v(3)
      integer v_min(3)
      integer v_len(3)
      integer three_to_one_lenf2pywrap
      end subroutine f2pywrap_third_order_centering_three_to_one_len 
      subroutine f2pywrap_third_order_centering_three_to_one (three_to_o&
     &nef2pywrap, v, v_min, v_max)
      integer v(3)
      integer v_min(3)
      integer v_max(3)
      integer three_to_onef2pywrap
      end subroutine f2pywrap_third_order_centering_three_to_one 
      subroutine f2pywrap_third_order_centering_one_to_three_len (one_to&
     &_three_lenf2pywrap, j, v_min, v_len)
      integer j
      integer v_min(3)
      integer v_len(3)
      integer one_to_three_lenf2pywrap(3)
      end subroutine f2pywrap_third_order_centering_one_to_three_len 
      subroutine f2pywrap_third_order_centering_one_to_three (one_to_thr&
     &eef2pywrap, j, v_min, v_max)
      integer j
      integer v_min(3)
      integer v_max(3)
      integer one_to_threef2pywrap(3)
      end subroutine f2pywrap_third_order_centering_one_to_three 
      subroutine f2pywrap_third_order_centering_min_el_wise_2 (min_el_wi&
     &se_2f2pywrap, a, b)
      integer a(3)
      integer b(3)
      integer min_el_wise_2f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_min_el_wise_2 
      subroutine f2pywrap_third_order_centering_max_el_wise_2 (max_el_wi&
     &se_2f2pywrap, a, b)
      integer a(3)
      integer b(3)
      integer max_el_wise_2f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_max_el_wise_2 
      subroutine f2pywrap_third_order_centering_min_el_wise_3 (min_el_wi&
     &se_3f2pywrap, a, b, c)
      integer a(3)
      integer b(3)
      integer c(3)
      integer min_el_wise_3f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_min_el_wise_3 
      subroutine f2pywrap_third_order_centering_max_el_wise_3 (max_el_wi&
     &se_3f2pywrap, a, b, c)
      integer a(3)
      integer b(3)
      integer c(3)
      integer max_el_wise_3f2pywrap(3)
      end subroutine f2pywrap_third_order_centering_max_el_wise_3 
      subroutine f2pywrap_third_order_centering_cryst_to_cart (cryst_to_&
     &cartf2pywrap, v, alat)
      integer v(3)
      real(kind=8) alat(3,3)
      real(kind=8) cryst_to_cartf2pywrap(3)
      end subroutine f2pywrap_third_order_centering_cryst_to_cart
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(analysis,center,center_sparse,pre_center,assign&
     &,f2pywrap_third_order_centering_within_dmax,f2pywrap_third_order_c&
     &entering_compute_perimeter,f2pywrap_third_order_centering_three_to&
     &_one_len,f2pywrap_third_order_centering_three_to_one,f2pywrap_thir&
     &d_order_centering_one_to_three_len,f2pywrap_third_order_centering_&
     &one_to_three,f2pywrap_third_order_centering_min_el_wise_2,f2pywrap&
     &_third_order_centering_max_el_wise_2,f2pywrap_third_order_centerin&
     &g_min_el_wise_3,f2pywrap_third_order_centering_max_el_wise_3,f2pyw&
     &rap_third_order_centering_cryst_to_cart)
      end subroutine f2pyinitthird_order_centering

      subroutine f2pywrap_third_order_cond_centering_norm (normf2pywrap,&
     & r)
      use third_order_cond_centering, only : norm
      real(kind=8) r(3)
      real(kind=8) normf2pywrap
      normf2pywrap = norm(r)
      end subroutine f2pywrap_third_order_cond_centering_norm
      subroutine f2pywrap_third_order_cond_centering_norma2 (norma2f2pyw&
     &rap, m, f2py_m_d0, f2py_m_d1)
      use third_order_cond_centering, only : norma2
      integer f2py_m_d0
      integer f2py_m_d1
      real(kind=8) m(f2py_m_d0,f2py_m_d1)
      real(kind=8) norma2f2pywrap
      norma2f2pywrap = norma2(m)
      end subroutine f2pywrap_third_order_cond_centering_norma2
      subroutine f2pywrap_third_order_cond_centering_norma3 (norma3f2pyw&
     &rap, m, f2py_m_d0, f2py_m_d1, f2py_m_d2)
      use third_order_cond_centering, only : norma3
      integer f2py_m_d0
      integer f2py_m_d1
      integer f2py_m_d2
      real(kind=8) m(f2py_m_d0,f2py_m_d1,f2py_m_d2)
      real(kind=8) norma3f2pywrap
      norma3f2pywrap = norma3(m)
      end subroutine f2pywrap_third_order_cond_centering_norma3
      subroutine f2pywrap_third_order_cond_centering_dot (dotf2pywrap, v&
     &, m)
      use third_order_cond_centering, only : dot
      real(kind=8) v(3)
      real(kind=8) m(3,3)
      real(kind=8) dotf2pywrap(3)
      dotf2pywrap = dot(v, m)
      end subroutine f2pywrap_third_order_cond_centering_dot
      
      subroutine f2pyinitthird_order_cond_centering(f2pysetupfunc)
      use third_order_cond_centering, only : check_permutation_symmetry
      use third_order_cond_centering, only : apply_permutation_symmetry
      use third_order_cond_centering, only : apply_permutation_symmetry_&
     &local
      use third_order_cond_centering, only : number_of_triplets
      use third_order_cond_centering, only : find_triplets
      use third_order_cond_centering, only : distribute_fc3
      use third_order_cond_centering, only : apply_asr
      use third_order_cond_centering, only : find_unique_rvec
      interface 
      subroutine f2pywrap_third_order_cond_centering_norm (normf2pywrap,&
     & r)
      real(kind=8) r(3)
      real(kind=8) normf2pywrap
      end subroutine f2pywrap_third_order_cond_centering_norm 
      subroutine f2pywrap_third_order_cond_centering_norma2 (norma2f2pyw&
     &rap, m, f2py_m_d0, f2py_m_d1)
      integer f2py_m_d0
      integer f2py_m_d1
      real(kind=8) m(f2py_m_d0,f2py_m_d1)
      real(kind=8) norma2f2pywrap
      end subroutine f2pywrap_third_order_cond_centering_norma2 
      subroutine f2pywrap_third_order_cond_centering_norma3 (norma3f2pyw&
     &rap, m, f2py_m_d0, f2py_m_d1, f2py_m_d2)
      integer f2py_m_d0
      integer f2py_m_d1
      integer f2py_m_d2
      real(kind=8) m(f2py_m_d0,f2py_m_d1,f2py_m_d2)
      real(kind=8) norma3f2pywrap
      end subroutine f2pywrap_third_order_cond_centering_norma3 
      subroutine f2pywrap_third_order_cond_centering_dot (dotf2pywrap, v&
     &, m)
      real(kind=8) v(3)
      real(kind=8) m(3,3)
      real(kind=8) dotf2pywrap(3)
      end subroutine f2pywrap_third_order_cond_centering_dot
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(check_permutation_symmetry,apply_permutation_sy&
     &mmetry,apply_permutation_symmetry_local,number_of_triplets,find_tr&
     &iplets,distribute_fc3,apply_asr,find_unique_rvec,f2pywrap_third_or&
     &der_cond_centering_norm,f2pywrap_third_order_cond_centering_norma2&
     &,f2pywrap_third_order_cond_centering_norma3,f2pywrap_third_order_c&
     &ond_centering_dot)
      end subroutine f2pyinitthird_order_cond_centering

      subroutine f2pywrap_third_order_cond_f_bose (f_bosef2pywrap, freq,&
     & t)
      use third_order_cond, only : f_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      f_bosef2pywrap = f_bose(freq, t)
      end subroutine f2pywrap_third_order_cond_f_bose
      subroutine f2pywrap_third_order_cond_df_bose (df_bosef2pywrap, fre&
     &q, t)
      use third_order_cond, only : df_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      df_bosef2pywrap = df_bose(freq, t)
      end subroutine f2pywrap_third_order_cond_df_bose
      subroutine f2pywrap_third_order_cond_gaussian_function (gaussian_f&
     &unctionf2pywrap, x, sigma)
      use third_order_cond, only : gaussian_function
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) gaussian_functionf2pywrap
      gaussian_functionf2pywrap = gaussian_function(x, sigma)
      end subroutine f2pywrap_third_order_cond_gaussian_function
      subroutine f2pywrap_third_order_cond_cinv (cinvf2pywrap, a, f2py_a&
     &_d0, f2py_a_d1)
      use third_order_cond, only : cinv
      integer f2py_a_d0
      integer f2py_a_d1
      complex(kind=8) a(f2py_a_d0,f2py_a_d1)
      complex(kind=8) cinvf2pywrap(size(a, 1),size(a, 2))
      cinvf2pywrap = cinv(a)
      end subroutine f2pywrap_third_order_cond_cinv
      
      subroutine f2pyinitthird_order_cond(f2pysetupfunc)
      use third_order_cond, only : interpol_v2
      use third_order_cond, only : interpol_v3
      use third_order_cond, only : compute_full_dynamic_bubble_single
      use third_order_cond, only : compute_diag_dynamic_bubble_single
      use third_order_cond, only : compute_perturb_selfnrg_single
      use third_order_cond, only : compute_spectralf_diag_single
      use third_order_cond, only : lambda_dynamic_single
      use third_order_cond, only : lambda_dynamic_value_single
      use third_order_cond, only : calculate_spectral_function
      use third_order_cond, only : calculate_spectral_function_mode_mixi&
     &ng
      use third_order_cond, only : calculate_spectral_function_cartesian
      use third_order_cond, only : bose_freq
      use third_order_cond, only : eq_freq
      use third_order_cond, only : eliminate_transl
      interface 
      subroutine f2pywrap_third_order_cond_f_bose (f_bosef2pywrap, freq,&
     & t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      end subroutine f2pywrap_third_order_cond_f_bose 
      subroutine f2pywrap_third_order_cond_df_bose (df_bosef2pywrap, fre&
     &q, t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      end subroutine f2pywrap_third_order_cond_df_bose 
      subroutine f2pywrap_third_order_cond_gaussian_function (gaussian_f&
     &unctionf2pywrap, x, sigma)
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) gaussian_functionf2pywrap
      end subroutine f2pywrap_third_order_cond_gaussian_function 
      subroutine f2pywrap_third_order_cond_cinv (cinvf2pywrap, a, f2py_a&
     &_d0, f2py_a_d1)
      integer f2py_a_d0
      integer f2py_a_d1
      complex(kind=8) a(f2py_a_d0,f2py_a_d1)
      complex(kind=8) cinvf2pywrap(size(a, 1),size(a, 2))
      end subroutine f2pywrap_third_order_cond_cinv
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(interpol_v2,interpol_v3,compute_full_dynamic_bu&
     &bble_single,compute_diag_dynamic_bubble_single,compute_perturb_sel&
     &fnrg_single,compute_spectralf_diag_single,lambda_dynamic_single,la&
     &mbda_dynamic_value_single,calculate_spectral_function,calculate_sp&
     &ectral_function_mode_mixing,calculate_spectral_function_cartesian,&
     &bose_freq,eq_freq,f2pywrap_third_order_cond_f_bose,f2pywrap_third_&
     &order_cond_df_bose,f2pywrap_third_order_cond_gaussian_function,eli&
     &minate_transl,f2pywrap_third_order_cond_cinv)
      end subroutine f2pyinitthird_order_cond

      subroutine f2pywrap_third_order_bubble_f_bose (f_bosef2pywrap, fre&
     &q, t)
      use third_order_bubble, only : f_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      f_bosef2pywrap = f_bose(freq, t)
      end subroutine f2pywrap_third_order_bubble_f_bose
      subroutine f2pywrap_third_order_bubble_df_bose (df_bosef2pywrap, f&
     &req, t)
      use third_order_bubble, only : df_bose
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      df_bosef2pywrap = df_bose(freq, t)
      end subroutine f2pywrap_third_order_bubble_df_bose
      
      subroutine f2pyinitthird_order_bubble(f2pysetupfunc)
      use third_order_bubble, only : compute_static_bubble
      use third_order_bubble, only : compute_dynamic_bubble
      use third_order_bubble, only : compute_diag_dynamic_bubble
      use third_order_bubble, only : compute_perturb_selfnrg
      use third_order_bubble, only : compute_spectralf
      use third_order_bubble, only : compute_spectralf_diag
      use third_order_bubble, only : lambda
      use third_order_bubble, only : lambda_dynamic
      use third_order_bubble, only : lambda_dynamic_value
      use third_order_bubble, only : bose_freq
      use third_order_bubble, only : invzmat
      use third_order_bubble, only : eliminate_transl
      interface 
      subroutine f2pywrap_third_order_bubble_f_bose (f_bosef2pywrap, fre&
     &q, t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) f_bosef2pywrap
      end subroutine f2pywrap_third_order_bubble_f_bose 
      subroutine f2pywrap_third_order_bubble_df_bose (df_bosef2pywrap, f&
     &req, t)
      real(kind=8) freq
      real(kind=8) t
      real(kind=8) df_bosef2pywrap
      end subroutine f2pywrap_third_order_bubble_df_bose
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(compute_static_bubble,compute_dynamic_bubble,co&
     &mpute_diag_dynamic_bubble,compute_perturb_selfnrg,compute_spectral&
     &f,compute_spectralf_diag,lambda,lambda_dynamic,lambda_dynamic_valu&
     &e,bose_freq,f2pywrap_third_order_bubble_f_bose,f2pywrap_third_orde&
     &r_bubble_df_bose,invzmat,eliminate_transl)
      end subroutine f2pyinitthird_order_bubble

      
      subroutine f2pyinitthird_order_interpol(f2pysetupfunc)
      use third_order_interpol, only : interpol
      external f2pysetupfunc
      call f2pysetupfunc(interpol)
      end subroutine f2pyinitthird_order_interpol


